"""
Stage-1 attribution fine-tuning with HYPERBOLIC ENTAILMENT CONES.

Each image of class c (e.g. "real" or "FLUX") is pushed inside the entailment
cone of the corresponding fixed text anchor:
  - "A real image"
  - "A synthetic image generated by FLUX"
and outside the cones of all other classes. No content captions are used in
the training objective — only the class anchors. At inference time, an image
is classified by projecting it into Lorentz space and picking the anchor whose
cone it sits in.

Usage:
    CUDA_VISIBLE_DEVICES=0,1,2,3 python train_attribution.py \\
        --dataset_path  $WORK/hyp_fine_tuning/iab_dataset \\
        --captions_dir  $WORK/hyp_fine_tuning/iab_captions \\
        --generators    real FLUX \\
        --semantics     COCO cat dog wild FFHQ celebahq bedroom church classroom ImageNet-1k \\
        --clip_name     openai/clip-vit-large-patch14 \\
        --output        $WORK/hyp_fine_tuning/checkpoints/attribution_FLUX_vitl14.pt
"""
import argparse
import os
from pathlib import Path

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.amp import GradScaler, autocast
from torch.utils.data import DataLoader, WeightedRandomSampler
from tqdm import tqdm
from transformers import CLIPTokenizer

from data.iab_clip_dataset import IABCLIPDataset
from geometry.lorentz import exp_map0, half_aperture, log_map0
from models.attribution_clip import AttributionCLIP
from losses.attribution_loss import EntailmentConeLoss, predict_class


# Class-anchor text templates. Order matters: this defines the integer labels.
def build_anchors(generators: list[str],
                  prompts_path: str | None = None) -> tuple[list[str], list[str]]:
    """
    Returns (class_names, anchor_texts) in a fixed order.
    class_names[i] is the generator string ("real", "FLUX", ...) used in the dataset;
    anchor_texts[i] is the natural-language anchor encoded by CLIP.

    Default: two templates, so 21 of the 22 anchors differ by a single token and
    CLIP embeds them almost collinearly. `prompts_path` points at a JSON map
    {class_name: sentence} (see data/anchor_prompts_structural.json) whose
    sentences differ in FORM, which spreads the anchors out at init.
    """
    ordered: list[str] = []
    if "real" in generators:
        ordered.append("real")
    for g in generators:
        if g != "real":
            ordered.append(g)

    if prompts_path:
        import json
        with open(prompts_path) as f:
            prompts = json.load(f)
        missing = [c for c in ordered if c not in prompts]
        if missing:
            raise ValueError(f"{prompts_path} has no prompt for {missing}")
        return ordered, [prompts[c] for c in ordered]

    anchor_texts = []
    for c in ordered:
        if c == "real":
            anchor_texts.append("A real image")
        else:
            anchor_texts.append(f"A synthetic image generated by {c}")
    return ordered, anchor_texts


def parse_args():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--dataset_path",   required=True)
    p.add_argument("--captions_dir",   required=True)
    p.add_argument("--generators",     nargs="+", default=["real", "FLUX"])
    p.add_argument("--semantics",      nargs="+",
                   default=["COCO", "cat", "dog", "wild", "FFHQ", "celebahq",
                            "bedroom", "church", "classroom", "ImageNet-1k"])
    p.add_argument("--output",         default="attribution_checkpoint_FLUX.pt")
    p.add_argument("--clip_name",      default="openai/clip-vit-base-patch32")
    p.add_argument("--lora_r",         type=int,   default=8)
    p.add_argument("--lora_alpha",     type=int,   default=16)
    p.add_argument("--hyperbolic_dim", type=int,   default=128)
    p.add_argument("--curv",           type=float, default=1.0)
    p.add_argument("--min_radius",     type=float, default=0.1)
    p.add_argument("--margin",         type=float, default=0.1)
    p.add_argument("--lambda_neg",     type=float, default=1.0)
    p.add_argument("--lambda_cap_in_class", type=float, default=0.0,
                   help="Hierarchical: weight of caption-in-class-anchor cone term.")
    p.add_argument("--lambda_img_in_cap",   type=float, default=0.0,
                   help="Hierarchical: weight of image-in-own-caption cone term "
                        "(batch negatives).")
    p.add_argument("--no_captions", action="store_true", default=False,
                   help="Pure base attribution loss: forces BOTH caption terms "
                        "(cap_in_class + img_in_cap) to 0 and trains on ALL images (no "
                        "caption requirement) → same sample set as the baselines.")
    p.add_argument("--require_caption", action="store_true", default=False,
                   help="Force training on the captioned-images subset even when the "
                        "caption loss terms are off. Lets the caption on/off ablation run "
                        "on the SAME subset (only the loss varies, not the data).")
    p.add_argument("--anchor_init", choices=["text", "image_centroid", "text_free"],
                   default="text",
                   help="'text' (default): anchors are the class text prompts encoded by "
                        "CLIP at every step (they still move, through the text-encoder LoRA). "
                        "'image_centroid': anchors are FREE parameters in tangent space, "
                        "initialised at the per-class mean of the training image embeddings "
                        "(one forward pass before training) — no text dependency. "
                        "'text_free': free parameters too, but initialised at the encoded "
                        "PROMPTS and allowed to drift only by a learned amount (see "
                        "--anchor_drift_init); at step 0 it is identical to 'text'.")
    p.add_argument("--anchor_prompts", type=str, default=None,
                   help="JSON map {class_name: sentence} replacing the two default templates "
                        "(e.g. data/anchor_prompts_structural.json). Used by both 'text' and "
                        "'text_free'. Saved into the checkpoint, and the eval re-encodes THOSE "
                        "sentences — never the defaults.")
    p.add_argument("--anchor_drift_init", type=float, default=0.1,
                   help="'text_free' only: initial value of the single learned scalar s in "
                        "t_c = t0_c + s·δ_c (δ init 0). Small s means the anchors start pinned "
                        "to the prompts and the model decides how far to move them.")
    p.add_argument("--anchor_init_norm", type=float, default=2.0,
                   help="Common tangent-space radius the FREE anchors (image_centroid and "
                        "text_free) are rescaled to at init "
                        "(only their directions carry the information; the radius sets "
                        "the initial cone width, ψ = asin(2·min_radius/‖t‖)). 0 keeps the raw "
                        "scale, which is tiny at init and degenerates every cone to a halfspace.")
    p.add_argument("--anchor_init_cache", type=str, default=None,
                   help="Cache file for the CLIP-space class means. Reused across runs (LoRA is "
                        "zero-init, so the pre-pass output is run-independent) → the ~20 min "
                        "forward pass over the train split happens once.")
    p.add_argument("--train_augment", action="store_true", default=False,
                   help="Random corruption augmentation (JPEG / blur / downsample, see "
                        "data.degradations.random_degradation) on the TRAIN split only. NOTE: "
                        "these are the test-time corruption families → report such a run with an "
                        "asterisk, it is not head-to-head comparable with the baselines.")
    p.add_argument("--aug_policy", choices=["corruption", "omnidfa"], default="corruption",
                   help="Which policy --train_augment applies. 'corruption' (default): the three "
                        "test-time families with continuously sampled parameters. 'omnidfa': "
                        "Table 8 of arXiv 2509.25682 — JPEG q75-95, resize 0.5-2.0, hflip, "
                        "RandAugment (no shear/translate), blur sigma 0.1-2.0. The omnidfa ranges "
                        "cover only DS0.5 of the seven test levels, so its asterisk is much "
                        "weaker than 'corruption''s.")
    p.add_argument("--mixup_alpha",    type=float, default=0.0,
                   help="Manifold mixup in the tangent space at the origin (0 disables it). "
                        "λ~Beta(α,α) mixes the batch with a permutation of itself and the cone "
                        "loss is evaluated twice, weighted λ / 1-λ. Unlike --train_augment this "
                        "shows the model NO corruption, so a run stays head-to-head comparable "
                        "with the baselines: it is the mechanism repmix uses (its ImageNet-C "
                        "perturbation is commented out in dataset_repmix.py) and repmix is the "
                        "only method that holds up under JPEG without seeing degradations.")
    p.add_argument("--mixup_at", choices=["clip", "tangent"], default="clip",
                   help="WHERE the batch is mixed. Mixup only regularises the layers ABOVE the "
                        "mixing point, since they are the ones that receive a mixed vector. "
                        "'clip' mixes the CLIP embedding, so the projection head is trained on "
                        "mixed inputs. 'tangent' mixes after the head, where the only thing left "
                        "is the parameter-free exp_map0 — it reshapes the loss surface but no "
                        "layer ever processes a mixed vector. 'tangent' reproduces the "
                        "attribution_22cls_mixup0.2 checkpoint; 'clip' is the better default.")
    p.add_argument("--blackout_max",   type=float, default=0.0,
                   help="Random pixel blackout on the TRAIN split (0 disables it). Per sample "
                        "λ~U(0, blackout_max) of the pixels are set to BLACK, drawn i.i.d. and "
                        "shared across the 3 channels. Unlike --train_augment none of the three "
                        "test corruption families (JPEG/blur/downsample) is involved → no "
                        "asterisk. Unlike --mixup_alpha the label stays single, so the cone loss "
                        "is called ONCE: no double positive hinge, and λ is a true intensity "
                        "instead of a choice of dominant class.")
    p.add_argument("--lambda_norm",    type=float, default=0.0,
                   help="Weight of the anchor-norm regulariser (0 disables it).")
    p.add_argument("--target_norm",    type=float, default=0.0,
                   help="Target ‖t_anchor‖. With curv=1, ψ ≈ π/8 at ‖t‖≈2.6, π/16 at ‖t‖≈5.")
    p.add_argument("--lambda_ce",      type=float, default=0.0,
                   help="Weight of a cross-entropy term on softmax(-ξ/τ) (0 disables it, and "
                        "the loss is then bit-identical to before). The cone hinge saturates: "
                        "once an image is inside its own cone the gradient is zero, and the "
                        "negative term is averaged over K-1 classes so each wrong class weighs "
                        "λ_neg/21. Nothing therefore optimises the RANKING of ξ, which is what "
                        "inference (argmin ξ) actually uses — hence AUC that holds up while "
                        "top-1 collapses under JPEG. The CE penalises probability mass on wrong "
                        "classes in proportion to how close they are. Inference is unchanged: "
                        "argmin ξ is scale-invariant, so τ never reaches the eval.")
    p.add_argument("--ce_tau_init",    type=float, default=1.0,
                   help="Initial temperature of the --lambda_ce term. τ = softplus(param) is "
                        "LEARNED: the exterior angles live in [0, π], so a fixed τ=1 is an "
                        "arbitrary choice of softmax sharpness (same reasoning as CLIP's "
                        "logit_scale).")
    p.add_argument("--batch_size",     type=int,   default=256)
    p.add_argument("--num_epochs",     type=int,   default=10)
    p.add_argument("--lr",             type=float, default=5e-5)
    p.add_argument("--weight_decay",   type=float, default=0.01)
    p.add_argument("--val_frac",       type=float, default=0.2)
    p.add_argument("--split_scheme",   choices=["caption", "stratified"], default="caption",
                   help="'stratified' mirrors the comparison baselines' 80/10/10 label split "
                        "(disjoint train/val/test) for a leakage-free fair comparison. "
                        "'caption' is the legacy caption-presence split.")
    p.add_argument("--test_frac",      type=float, default=0.1,
                   help="Held-out test fraction; only used with --split_scheme stratified.")
    p.add_argument("--split_manifest", type=str, default=None,
                   help="JSON split manifest from dump_split_manifest.py. Ours is trained "
                        "ONLY on the manifest's 'train' images (strict data parity with the "
                        "baselines) and never on their val/test → leakage-free, and ours can "
                        "be evaluated on the baselines' EXACT test images (Path 1).")
    p.add_argument("--seed",           type=int,   default=42)
    p.add_argument("--max_per_class",  type=int,   default=None)
    p.add_argument("--num_workers",    type=int,   default=8)
    return p.parse_args()


def make_balanced_sampler(dataset: IABCLIPDataset) -> WeightedRandomSampler:
    """K-way balanced sampler: every class sampled with equal probability."""
    from collections import Counter
    counts = Counter(g for _, g, _ in dataset.samples)
    if len(counts) < 2:
        raise RuntimeError(f"Dataset needs at least 2 classes, got: {dict(counts)}")
    if any(n == 0 for n in counts.values()):
        raise RuntimeError(f"Empty class in dataset: {dict(counts)}")
    weights = [1.0 / counts[g] for _, g, _ in dataset.samples]
    print(f"Balanced sampler classes: {dict(counts)}")
    return WeightedRandomSampler(weights, num_samples=len(dataset), replacement=True)


@torch.no_grad()
def encode_anchors(model, anchor_texts: list[str], tokenizer, device: str) -> torch.Tensor:
    """Encode the fixed text anchors and return their Lorentz-space coords (K, D)."""
    tok = tokenizer(anchor_texts, return_tensors="pt", padding="max_length",
                    truncation=True, max_length=77)
    x_anc, _ = model.encode_text(tok["input_ids"].to(device),
                                 tok["attention_mask"].to(device))
    return x_anc


@torch.no_grad()
def class_centroids(core, dataset, class_names, args, device,
                    feat_fn=None, cache_path=None) -> torch.Tensor:
    """Per-class mean of the CLIP-space training image embeddings → (K, D_clip).

    Text-free anchor initialisation: one forward pass over the whole train split
    through the vision encoder. LoRA is zero-initialised, so at this point the
    features are exactly the frozen CLIP ones — the result depends only on the
    backbone and the data, which is why it can be cached across runs.

    feat_fn/cache_path override the CLIP-space encoder and the cache file, so a
    second branch (e.g. the spectral one of patch_freq_attribution) can build its
    own anchors with the same machinery.
    """
    name_to_idx = {n: i for i, n in enumerate(class_names)}
    K = len(class_names)
    feat_fn = feat_fn or core._clip_image

    cache_path = cache_path or args.anchor_init_cache
    cache = Path(cache_path) if cache_path else None
    if cache is not None and cache.exists():
        blob = torch.load(cache, map_location="cpu", weights_only=False)
        if blob["class_names"] != class_names:
            raise ValueError(
                f"anchor cache {cache} was built for {blob['class_names']}, "
                f"not for {class_names}")
        print(f"Anchor centroids: loaded from cache {cache}")
        return blob["mean_clip"]

    # Sequential loader: we want the true per-class mean, not the balanced-sampler
    # one. Augmentation off — centroids are always computed on clean images so the
    # clean and augmented runs start from the same anchors.
    was_aug, dataset.train_augment = dataset.train_augment, False
    was_training = core.training
    core.eval()
    loader = DataLoader(dataset, batch_size=args.batch_size, shuffle=False,
                        num_workers=args.num_workers, pin_memory=True)
    clip_dim = core.clip.base_model.model.config.projection_dim
    sums = torch.zeros(K, clip_dim, dtype=torch.float64, device=device)
    counts = torch.zeros(K, dtype=torch.long, device=device)
    for batch in tqdm(loader, desc="anchor centroids"):
        with autocast("cuda"):
            feats = feat_fn(batch["pixel_values"].to(device))
        labels = torch.tensor([name_to_idx[g] for g in batch["generator"]],
                              device=device, dtype=torch.long)
        sums.index_add_(0, labels, feats.double())
        counts.index_add_(0, labels, torch.ones_like(labels))
    dataset.train_augment = was_aug
    core.train(was_training)

    empty = [c for c, n in zip(class_names, counts.tolist()) if n == 0]
    if empty:
        raise RuntimeError(f"No training images for class(es) {empty} — cannot build anchors")
    mean_clip = F.normalize((sums / counts.unsqueeze(1)).float(), dim=-1).cpu()
    print("Anchor centroids (images per class): "
          + ", ".join(f"{c}={n}" for c, n in zip(class_names, counts.tolist())))

    if cache is not None:
        cache.parent.mkdir(parents=True, exist_ok=True)
        tmp = cache.with_suffix(cache.suffix + f".tmp{os.getpid()}")
        torch.save({"class_names": class_names, "mean_clip": mean_clip}, tmp)
        os.replace(tmp, cache)   # atomic: two jobs may race to build the cache
        print(f"Anchor centroids: cached → {cache}")
    return mean_clip


@torch.no_grad()
def run_validation(model_inner, val_loader, x_anc, class_names, device, curv) -> dict:
    model_inner.eval()

    per_class_correct = {c: 0 for c in class_names}
    per_class_total   = {c: 0 for c in class_names}

    for batch in tqdm(val_loader, desc="val", leave=False):
        pixel = batch["pixel_values"].to(device)
        with autocast("cuda"):
            x_img, _ = model_inner.encode_image(pixel)
        pred_idx = predict_class(x_img, x_anc, curv=curv)
        pred_names = [class_names[i] for i in pred_idx.tolist()]
        for pred, gt in zip(pred_names, batch["generator"]):
            per_class_total[gt] += 1
            per_class_correct[gt] += int(pred == gt)

    total = sum(per_class_total.values())
    correct = sum(per_class_correct.values())
    per_class_acc = {
        c: (per_class_correct[c] / per_class_total[c]) if per_class_total[c] > 0 else 0.0
        for c in class_names
    }
    balanced = sum(per_class_acc.values()) / len(class_names)
    return {
        "overall_acc":   correct / total if total else 0.0,
        "balanced_acc":  balanced,
        "per_class_acc": per_class_acc,
        "total":         total,
    }


def main():
    args = parse_args()
    if args.no_captions:
        args.lambda_cap_in_class = 0.0
        args.lambda_img_in_cap = 0.0
    device = "cuda" if torch.cuda.is_available() else "cpu"
    # Covers the projection-head init and the balanced sampler's draw order (the
    # dataset splits already seed their own RNG). NOT bit-exact: GPU reduction
    # order still varies, so two seeded runs agree closely, not to the last digit.
    torch.manual_seed(args.seed)
    print(f"Seed: {args.seed}")

    class_names, anchor_texts = build_anchors(args.generators, args.anchor_prompts)
    name_to_idx = {n: i for i, n in enumerate(class_names)}
    if args.anchor_init != "text" and (args.lambda_cap_in_class > 0
                                       or args.lambda_img_in_cap > 0):
        # Free anchors take the text encoder out of the objective (it is used at most
        # once, at init), so the caption terms have no anchor that keeps moving with
        # the captions. Same reasoning for both free modes.
        raise ValueError(f"--anchor_init {args.anchor_init} makes the anchors free "
                         f"parameters; the caption terms have no class anchor to attach "
                         f"to. Use --no_captions.")
    if args.anchor_init == "image_centroid":
        print(f"Class anchors: image centroids (text-free), {len(class_names)} classes")
        for i, c in enumerate(class_names):
            print(f"  [{i}] {c}")
    else:
        src = args.anchor_prompts or "default templates"
        print(f"Class anchors ({args.anchor_init}, from {src}):")
        for i, (c, t) in enumerate(zip(class_names, anchor_texts)):
            print(f"  [{i}] {c:14s} → \"{t}\"")

    # ── Split manifest (Path 1: strict data parity + leakage-free vs baselines) ──
    # With a manifest: train on ALL harness-train images and validate on the harness
    # VAL split — no internal re-split (avoids the double val carve that shrank the
    # train set) and no data loss. require_caption follows whether any caption term
    # is active. Without a manifest: legacy caption-based split.
    use_caps = (args.lambda_cap_in_class > 0 or args.lambda_img_in_cap > 0)
    # Training set membership: captioned-only if any caption term is active OR if
    # --require_caption forces it (caption on/off ablation on the same subset).
    # Decoupled from use_caps so caption-OFF can share the captioned subset.
    req_cap = use_caps or args.require_caption
    train_include = val_include = None
    if args.split_manifest:
        import json
        with open(args.split_manifest) as f:
            man = json.load(f)
        train_include = set(man["train"])
        val_include = set(man["val"])
        print(f"Split manifest: {len(train_include)} train + {len(val_include)} val images "
              f"(require_caption={req_cap}; harness val used for model selection)")

    # ── Datasets ──────────────────────────────────────────────────────────────
    print("\n=== Train split ===")
    if train_include is not None:
        train_ds = IABCLIPDataset(
            root=args.dataset_path, captions_dir=args.captions_dir,
            generators=args.generators, semantics=args.semantics,
            processor_name=args.clip_name, max_per_class=args.max_per_class,
            split="all", seed=args.seed,
            include_paths=train_include, require_caption=req_cap,
        )
        print("\n=== Val split (harness val) ===")
        val_ds = IABCLIPDataset(
            root=args.dataset_path, captions_dir=args.captions_dir,
            generators=args.generators, semantics=args.semantics,
            processor_name=args.clip_name, max_per_class=args.max_per_class,
            split="all", seed=args.seed,
            include_paths=val_include, require_caption=False, include_uncaptioned=True,
        )
    else:
        train_ds = IABCLIPDataset(
            root=args.dataset_path, captions_dir=args.captions_dir,
            generators=args.generators, semantics=args.semantics,
            processor_name=args.clip_name, max_per_class=args.max_per_class,
            split="train", val_frac=args.val_frac, seed=args.seed,
            split_scheme=args.split_scheme, test_frac=args.test_frac,
            require_caption=req_cap,
        )
        print("\n=== Val split ===")
        val_ds = IABCLIPDataset(
            root=args.dataset_path, captions_dir=args.captions_dir,
            generators=args.generators, semantics=args.semantics,
            processor_name=args.clip_name, max_per_class=args.max_per_class,
            split="val", val_frac=args.val_frac, seed=args.seed,
            include_uncaptioned=True, split_scheme=args.split_scheme, test_frac=args.test_frac,
            require_caption=use_caps,
        )

    # Augmentation on the train split only: the val split stays clean so model
    # selection is not measured under corruption.
    train_ds.train_augment = args.train_augment
    train_ds.aug_policy = args.aug_policy
    if args.train_augment:
        what = ("random JPEG / blur / downsample" if args.aug_policy == "corruption"
                else "OmniDFA Table 8 (JPEG 75-95 / resize / hflip / RandAugment / blur)")
        print(f"Train-time augmentation: ON  policy={args.aug_policy}  ({what}) — "
              "results are NOT head-to-head comparable with the baselines.")

    # "Black" AFTER the CLIP normalisation is (0 − mean)/std ≈ −1.79, not 0 — zeroing
    # the normalised tensor would paint the CLIP mean colour (grey) instead.
    black = -(torch.tensor(train_ds.processor.image_mean, device=device)
              / torch.tensor(train_ds.processor.image_std, device=device)).view(1, 3, 1, 1)
    if args.blackout_max > 0:
        print(f"Blackout: λ~U(0,{args.blackout_max}) per sample")

    sampler = make_balanced_sampler(train_ds)
    train_loader = DataLoader(
        train_ds, batch_size=args.batch_size, sampler=sampler,
        num_workers=args.num_workers, pin_memory=True, drop_last=True,
    )
    val_loader = DataLoader(
        val_ds, batch_size=args.batch_size, shuffle=False,
        num_workers=args.num_workers, pin_memory=True,
    )

    # ── Model ─────────────────────────────────────────────────────────────────
    model = AttributionCLIP(
        clip_name=args.clip_name,
        lora_r=args.lora_r,
        lora_alpha=args.lora_alpha,
        hyperbolic_dim=args.hyperbolic_dim,
        curv=args.curv,
    ).to(device)

    # ── Anchors ───────────────────────────────────────────────────────────────
    # Two free-anchor modes, both producing a tangent-space starting point t0 whose
    # DIRECTIONS carry the information and whose radius is reset to a common value
    # (the raw radius out of the projection head is ~0.1 because of init_scale, and
    # that degenerates every cone into a halfspace):
    #   image_centroid — t0 = per-class mean of the training image embeddings, from
    #                    one pre-pass over the train split (single GPU, before the
    #                    DataParallel wrap). No text at all.
    #   text_free      — t0 = the encoded class PROMPTS. Same starting point as plain
    #                    'text' mode up to the common rescale, but from there the
    #                    anchors may drift by t = t0 + softplus(s)·δ, with δ init 0
    #                    and s a SINGLE learned scalar: the model decides how far to
    #                    move away from the prompts.
    anchor_tangent = None                      # image_centroid: the parameter itself
    anchor_t0 = anchor_delta = anchor_drift = None    # text_free

    # Tokenized anchors stay constant; only the text-encoder weights change.
    tokenizer = CLIPTokenizer.from_pretrained(args.clip_name)
    anchor_tok = tokenizer(anchor_texts, return_tensors="pt", padding="max_length",
                           truncation=True, max_length=77)
    anchor_ids  = anchor_tok["input_ids"].to(device)
    anchor_mask = anchor_tok["attention_mask"].to(device)

    if args.anchor_init != "text":
        with torch.no_grad():
            if args.anchor_init == "image_centroid":
                t0 = model.projection(
                    class_centroids(model, train_ds, class_names, args, device).to(device))
            else:
                _, t0 = model.encode_text(anchor_ids, anchor_mask)
            if args.anchor_init_norm > 0:
                t0 = F.normalize(t0, dim=-1) * args.anchor_init_norm
            t0 = t0.detach().float()

        if args.anchor_init == "image_centroid":
            anchor_tangent = nn.Parameter(t0)
        else:
            anchor_t0 = t0                                        # fixed reference
            anchor_delta = nn.Parameter(torch.zeros_like(t0))
            # s = softplus(raw): positive, unconstrained, one scalar for all classes.
            anchor_drift = nn.Parameter(
                torch.tensor(float(args.anchor_drift_init)).expm1().clamp(min=1e-6).log())

        with torch.no_grad():
            psi0 = half_aperture(exp_map0(t0, curv=args.curv),
                                 curv=args.curv, min_radius=args.min_radius)
            # Angular spread at init: if the anchors sit closer together than 2ψ their
            # cones overlap and the free parameters can collapse winner-take-all (this
            # is what killed mid-6.0 in the centroid run).
            d = F.normalize(t0, dim=-1)
            cos = (d @ d.T).clamp(-1, 1)
            iu = torch.triu_indices(len(class_names), len(class_names), offset=1)
            ang = torch.arccos(cos[iu[0], iu[1]])     # off-diagonal pairs only
        print(f"Anchor init ({args.anchor_init}): ‖t‖={t0.norm(dim=-1).mean():.2f}  "
              f"ψ={psi0.mean():.3f} rad  min∠={ang.min():.3f}  mean∠={ang.mean():.3f}  "
              f"(K={len(class_names)})")
        if ang.min() < 2 * psi0.mean():
            print(f"  ⚠️  closest anchor pair is inside 2ψ={2 * psi0.mean():.3f} rad — "
                  f"those cones overlap at init")
        if anchor_drift is not None:
            print(f"  drift scale s={F.softplus(anchor_drift).item():.3f} (learned)")

    def anchor_tangent_now():
        """Current tangent anchors (K, D_hyp), or None in plain 'text' mode."""
        if anchor_delta is not None:
            return anchor_t0 + F.softplus(anchor_drift) * anchor_delta
        return anchor_tangent

    if torch.cuda.device_count() > 1:
        print(f"Using {torch.cuda.device_count()} GPUs")
        model = nn.DataParallel(model)

    core = model.module if isinstance(model, nn.DataParallel) else model
    core.print_trainable_summary()

    # Built before the optimizer: with --lambda_ce it owns a learned temperature that
    # has to be in the parameter list.
    cone_loss = EntailmentConeLoss(
        curv=args.curv, min_radius=args.min_radius,
        margin=args.margin, lambda_neg=args.lambda_neg,
        lambda_cap_in_class=args.lambda_cap_in_class,
        lambda_img_in_cap=args.lambda_img_in_cap,
        lambda_norm=args.lambda_norm, target_norm=args.target_norm,
        lambda_ce=args.lambda_ce, ce_tau_init=args.ce_tau_init,
    ).to(device)

    trainable = core.trainable_parameters()
    for extra in (anchor_tangent, anchor_delta, anchor_drift):
        if extra is not None:
            trainable = trainable + [extra]
    trainable = trainable + list(cone_loss.parameters())
    optimizer = torch.optim.AdamW(
        trainable,
        lr=args.lr,
        weight_decay=args.weight_decay,
    )
    steps_per_epoch = len(train_loader)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=args.num_epochs * steps_per_epoch, eta_min=1e-6
    )
    scaler = GradScaler("cuda")
    if args.lambda_ce > 0:
        print(f"CE ranking term: λ_ce={args.lambda_ce}  τ_init={args.ce_tau_init} (learned)")
    if use_caps:
        print(f"Hierarchical mode: λ_cap_in_class={args.lambda_cap_in_class} "
              f"λ_img_in_cap={args.lambda_img_in_cap}")
    else:
        print("Base attribution loss only (no caption terms).")

    if args.mixup_alpha > 0:
        if use_caps:
            raise ValueError("--mixup_alpha needs --no_captions: mixing images but not their "
                             "captions makes L_img_in_cap meaningless.")
        mixup_beta = torch.distributions.Beta(args.mixup_alpha, args.mixup_alpha)
        print(f"Mixup: α={args.mixup_alpha} at '{args.mixup_at}'")
    mix_at_clip = args.mixup_alpha > 0 and args.mixup_at == "clip"

    best_balanced = -1.0
    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    # ── Training loop ─────────────────────────────────────────────────────────
    base_keys = ["loss_img_in_cls", "loss_cap_in_cls", "loss_img_in_cap", "loss_norm",
                 "cone_acc", "inside_img", "mean_psi_anc", "mean_xi_img_anc",
                 "mean_anc_norm"]
    cap_keys  = ["inside_cap", "inside_img_cap", "mean_psi_cap",
                 "mean_xi_cap_anc", "mean_xi_img_cap", "mean_cap_norm"]
    ce_keys   = ["loss_ce", "ce_tau"] if args.lambda_ce > 0 else []

    for epoch in range(1, args.num_epochs + 1):
        model.train()
        sums = {"loss": 0.0, **{k: 0.0 for k in base_keys + ce_keys}}
        if use_caps:
            sums.update({k: 0.0 for k in cap_keys})
        bar = tqdm(train_loader, desc=f"Epoch {epoch}/{args.num_epochs}")
        for step, batch in enumerate(bar, 1):
            pixel    = batch["pixel_values"].to(device)
            cap_ids  = batch["input_ids"].to(device)        # already tokenized augmented caption
            cap_mask = batch["attention_mask"].to(device)
            labels   = torch.tensor([name_to_idx[g] for g in batch["generator"]],
                                    device=device, dtype=torch.long)

            if args.blackout_max > 0:
                # One λ per sample, so a batch carries the whole spectrum of occlusion.
                # The mask is (B,1,H,W) → broadcast over the channels, i.e. the whole
                # pixel goes black. Applied on the full batch, before the DataParallel
                # scatter. The label is untouched: the cone loss below runs once.
                lam  = torch.rand(pixel.size(0), 1, 1, 1, device=device) * args.blackout_max
                mask = torch.rand(pixel.size(0), 1, *pixel.shape[-2:], device=device) < lam
                pixel = torch.where(mask, black.to(pixel.dtype), pixel)

            with autocast("cuda"):
                if use_caps:
                    x_img, x_cap = model(pixel, cap_ids, cap_mask)
                elif mix_at_clip:
                    # Stop before the projection head; the mix happens below and
                    # to_hyperbolic finishes the job on the primary GPU.
                    clip_emb = model(pixel, return_clip_emb=True)
                    x_cap = None
                else:
                    x_img = model(pixel)
                    x_cap = None
                t_anc = anchor_tangent_now()
                if t_anc is None:
                    x_anc, _ = core.encode_text(anchor_ids, anchor_mask)
            if t_anc is not None:
                # fp32, outside autocast: the hyperbolic ops are unstable in fp16
                # (same reason AttributionCLIP.to_hyperbolic disables autocast).
                with autocast("cuda", enabled=False):
                    x_anc = exp_map0(t_anc.float(), curv=args.curv)
            if args.mixup_alpha > 0:
                # EntailmentConeLoss is untouched — the mixed target is expressed by
                # calling it twice, exactly as the multi-view trainer folds views into
                # the batch. Only the mixing POINT differs between the two modes.
                with autocast("cuda", enabled=False):
                    lam = mixup_beta.sample().item()
                    if mix_at_clip:
                        e = clip_emb.float()
                        perm = torch.randperm(e.size(0), device=device)
                        # Re-normalise: _clip_image only ever emits unit vectors, and
                        # a convex combination of two of them is SHORTER. Without this
                        # every mixed sample would get a smaller tangent and land closer
                        # to the origin, turning mixup into a norm regulariser as well.
                        mixed = F.normalize(lam * e + (1 - lam) * e[perm], dim=-1)
                        x_mix, _ = core.to_hyperbolic(mixed)
                    else:
                        # Tangent space at the origin: exp_map0 is radial, so a convex
                        # combination there is the manifold-mixup analogue (mixing on
                        # the hyperboloid itself would need a geodesic).
                        perm = torch.randperm(x_img.size(0), device=device)
                        t = log_map0(x_img.float(), curv=args.curv)
                        x_mix = exp_map0(lam * t + (1 - lam) * t[perm], curv=args.curv)
                loss_a, stats = cone_loss(x_mix, x_anc, labels)
                loss_b, _     = cone_loss(x_mix, x_anc, labels[perm])
                loss = lam * loss_a + (1 - lam) * loss_b
            else:
                loss, stats = cone_loss(x_img, x_anc, labels, x_cap=x_cap)

            optimizer.zero_grad()
            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            nn.utils.clip_grad_norm_(trainable, 1.0)
            scaler.step(optimizer)
            scaler.update()
            scheduler.step()

            sums["loss"] += loss.item()
            for k in base_keys + ce_keys:
                sums[k] += stats[k].item()
            if use_caps:
                for k in cap_keys:
                    sums[k] += stats[k].item()

            if step % 25 == 0 or step == steps_per_epoch:
                post = {
                    "loss": f"{sums['loss']/step:.3f}",
                    "ic":   f"{sums['loss_img_in_cls']/step:.3f}",
                    "acc":  f"{sums['cone_acc']/step:.3f}",
                    "ψa":   f"{sums['mean_psi_anc']/step:.3f}",
                }
                if use_caps:
                    post["cc"] = f"{sums['loss_cap_in_cls']/step:.3f}"
                    post["ip"] = f"{sums['loss_img_in_cap']/step:.3f}"
                    post["ψc"] = f"{sums['mean_psi_cap']/step:.3f}"
                bar.set_postfix(**post)

        avg = {k: v / steps_per_epoch for k, v in sums.items()}
        line1 = (f"\nEpoch {epoch}: train loss={avg['loss']:.4f}  "
                 f"L_img_cls={avg['loss_img_in_cls']:.4f}")
        if use_caps:
            line1 += (f"  L_cap_cls={avg['loss_cap_in_cls']:.4f}"
                      f"  L_img_cap={avg['loss_img_in_cap']:.4f}")
        line1 += f"  L_norm={avg['loss_norm']:.4f}"
        if ce_keys:
            line1 += f"  L_ce={avg['loss_ce']:.4f}  τ={avg['ce_tau']:.3f}"
        if anchor_drift is not None:
            line1 += f"  drift_s={F.softplus(anchor_drift).item():.4f}"
        line1 += f"  lr={scheduler.get_last_lr()[0]:.2e}"
        print(line1)
        print(f"           cone_acc={100*avg['cone_acc']:.1f}%  "
              f"inside_img={100*avg['inside_img']:.1f}%  "
              f"ψ_anc={avg['mean_psi_anc']:.3f}  "
              f"ξ_img→anc={avg['mean_xi_img_anc']:.3f}  "
              f"‖t̄_anc‖={avg['mean_anc_norm']:.2f}")
        if use_caps:
            print(f"           inside_cap={100*avg['inside_cap']:.1f}%  "
                  f"inside_img_in_cap={100*avg['inside_img_cap']:.1f}%  "
                  f"ψ_cap={avg['mean_psi_cap']:.3f}  "
                  f"ξ_cap→anc={avg['mean_xi_cap_anc']:.3f}  "
                  f"ξ_img→cap={avg['mean_xi_img_cap']:.3f}  "
                  f"‖t̄_cap‖={avg['mean_cap_norm']:.2f}")

        # ── Validation ───────────────────────────────────────────────────────
        # Anchors under the CURRENT weights: text ones must be re-encoded, the free
        # ones come out of anchor_tangent_now(). eval() first — the text anchors must
        # not be encoded with LoRA dropout active.
        core.eval()
        with torch.no_grad():
            t_anc_val = anchor_tangent_now()
            if t_anc_val is None:
                x_anc_val, _ = core.encode_text(anchor_ids, anchor_mask)
            else:
                x_anc_val = exp_map0(t_anc_val.float(), curv=args.curv)
        val = run_validation(core, val_loader, x_anc_val, class_names, device, args.curv)
        print(f"  val: overall={100*val['overall_acc']:.1f}%  "
              f"balanced={100*val['balanced_acc']:.1f}%  ({val['total']} samples)")
        for c, a in val["per_class_acc"].items():
            print(f"    {c:10s}: {100*a:5.1f}%")

        # ── Save best checkpoint by balanced val accuracy ────────────────────
        if val["balanced_acc"] > best_balanced:
            best_balanced = val["balanced_acc"]
            torch.save(
                {
                    "lora_state":      core.clip.state_dict(),
                    "projection":      core.projection.state_dict(),
                    "clip_name":       args.clip_name,
                    "lora_r":          args.lora_r,
                    "lora_alpha":      args.lora_alpha,
                    "hyperbolic_dim":  args.hyperbolic_dim,
                    "curv":            args.curv,
                    "min_radius":      args.min_radius,
                    "class_names":     class_names,
                    "anchor_texts":    anchor_texts,
                    "anchor_init":     args.anchor_init,
                    "anchor_prompts":  args.anchor_prompts,
                    # Free-anchor modes only (image_centroid / text_free): the learned
                    # anchors in tangent space, in class_names order. Inference lifts
                    # them with exp_map0. None in 'text' mode, where the eval re-encodes
                    # anchor_texts instead.
                    "anchor_tangent":  (t_anc_val.detach().cpu()
                                        if t_anc_val is not None else None),
                    "anchor_drift":    (F.softplus(anchor_drift).item()
                                        if anchor_drift is not None else None),
                    "lambda_ce":       args.lambda_ce,
                    "ce_tau":          (F.softplus(cone_loss.ce_tau_raw).item()
                                        if args.lambda_ce > 0 else None),
                    "train_augment":   args.train_augment,
                    "aug_policy":      args.aug_policy,
                    "mixup_alpha":     args.mixup_alpha,
                    "mixup_at":        args.mixup_at,
                    "blackout_max":    args.blackout_max,
                    "generators":      args.generators,
                    "semantics":       args.semantics,
                    "val_balanced":    val["balanced_acc"],
                    "epoch":           epoch,
                },
                out_path,
            )
            print(f"  ↳ saved checkpoint (balanced val={100*best_balanced:.1f}%) → {out_path}")

    print(f"\nBest balanced val accuracy: {100*best_balanced:.1f}%  ({out_path})")


if __name__ == "__main__":
    main()
