"""
EUCLIDEAN BASELINE for attribution fine-tuning — the ablation that isolates the
contribution of hyperbolic geometry.

Identical to train_attribution.py in every respect that is not geometric:
  - same backbone (CLIP + LoRA on q_proj/v_proj of both encoders),
  - same projection-head capacity (clip_dim → clip_dim → embed_dim),
  - same fixed class anchors ("A real image" / "A synthetic image generated by X"),
  - same dataset, balanced K-way sampler, optimiser, LR schedule and budget.

The ONLY change is the geometry: embeddings live on the Euclidean unit sphere
and images are classified by COSINE SIMILARITY to the text anchors (scaled by a
learnable temperature) and trained with cross-entropy — i.e. trainable zero-shot
CLIP — instead of being lifted onto the Lorentz hyperboloid and matched by
entailment-cone exterior angle. No captions enter the objective (there is no
entailment hierarchy on the sphere); training is image-vs-anchor only.

Usage:
    CUDA_VISIBLE_DEVICES=0,1,2,3 python train_attribution_euclidean.py \\
        --dataset_path  $WORK/iab_dataset \\
        --captions_dir  $WORK/hyp_fine_tuning/iab_captions \\
        --generators    real FLUX \\
        --semantics     COCO cat dog wild FFHQ celebahq bedroom church classroom ImageNet-1k \\
        --clip_name     openai/clip-vit-large-patch14 \\
        --output        $WORK/checkpoints/attribution_euclidean_vitl14.pt
"""
import argparse
from pathlib import Path

import torch
import torch.nn as nn
from torch.amp import GradScaler, autocast
from torch.utils.data import DataLoader
from tqdm import tqdm
from transformers import CLIPTokenizer

from data.iab_clip_dataset import IABCLIPDataset
from models.euclidean_attribution_clip import EuclideanAttributionCLIP
from losses.euclidean_attribution_loss import PrototypeCELoss, predict_class
# Reuse the exact anchor construction and balanced sampler from the hyperbolic
# trainer so the two runs are sampling-identical.
from train_attribution import build_anchors, make_balanced_sampler


def parse_args():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--dataset_path",   required=True)
    p.add_argument("--captions_dir",   required=True)
    p.add_argument("--generators",     nargs="+", default=["real", "FLUX"])
    p.add_argument("--semantics",      nargs="+",
                   default=["COCO", "cat", "dog", "wild", "FFHQ", "celebahq",
                            "bedroom", "church", "classroom", "ImageNet-1k"])
    p.add_argument("--output",         default="attribution_euclidean.pt")
    p.add_argument("--clip_name",      default="openai/clip-vit-base-patch32")
    p.add_argument("--lora_r",         type=int,   default=8)
    p.add_argument("--lora_alpha",     type=int,   default=16)
    p.add_argument("--embed_dim",      type=int,   default=128,
                   help="Sphere embedding dim; mirror --hyperbolic_dim of the hyperbolic run.")
    p.add_argument("--logit_scale_init", type=float, default=2.6593,
                   help="Initial log-temperature (default log(1/0.07), the CLIP value).")
    p.add_argument("--batch_size",     type=int,   default=256)
    p.add_argument("--num_epochs",     type=int,   default=10)
    p.add_argument("--lr",             type=float, default=5e-5)
    p.add_argument("--weight_decay",   type=float, default=0.01)
    p.add_argument("--val_frac",       type=float, default=0.2)
    p.add_argument("--seed",           type=int,   default=42)
    p.add_argument("--max_per_class",  type=int,   default=None)
    p.add_argument("--num_workers",    type=int,   default=8)
    return p.parse_args()


@torch.no_grad()
def run_validation(model_inner, val_loader, anchor_ids, anchor_mask, class_names,
                   device) -> dict:
    model_inner.eval()
    # Anchors must be re-encoded under the current text-encoder weights.
    x_anc = model_inner.encode_text(anchor_ids, anchor_mask)

    per_class_correct = {c: 0 for c in class_names}
    per_class_total   = {c: 0 for c in class_names}

    for batch in tqdm(val_loader, desc="val", leave=False):
        pixel = batch["pixel_values"].to(device)
        with autocast("cuda"):
            x_img = model_inner.encode_image(pixel)
        pred_idx = predict_class(x_img.float(), x_anc.float())
        pred_names = [class_names[i] for i in pred_idx.tolist()]
        for pred, gt in zip(pred_names, batch["generator"]):
            per_class_total[gt] += 1
            per_class_correct[gt] += int(pred == gt)

    total = sum(per_class_total.values())
    correct = sum(per_class_correct.values())
    per_class_acc = {
        c: (per_class_correct[c] / per_class_total[c]) if per_class_total[c] > 0 else 0.0
        for c in class_names
    }
    balanced = sum(per_class_acc.values()) / len(class_names)
    return {
        "overall_acc":   correct / total if total else 0.0,
        "balanced_acc":  balanced,
        "per_class_acc": per_class_acc,
        "total":         total,
    }


def main():
    args = parse_args()
    device = "cuda" if torch.cuda.is_available() else "cpu"

    class_names, anchor_texts = build_anchors(args.generators)
    name_to_idx = {n: i for i, n in enumerate(class_names)}
    print("Class anchors:")
    for i, (c, t) in enumerate(zip(class_names, anchor_texts)):
        print(f"  [{i}] {c:8s} → \"{t}\"")

    # ── Datasets (identical splits to the hyperbolic run) ──────────────────────
    print("\n=== Train split ===")
    train_ds = IABCLIPDataset(
        root=args.dataset_path,
        captions_dir=args.captions_dir,
        generators=args.generators,
        semantics=args.semantics,
        processor_name=args.clip_name,
        max_per_class=args.max_per_class,
        split="train",
        val_frac=args.val_frac,
        seed=args.seed,
    )
    print("\n=== Val split ===")
    val_ds = IABCLIPDataset(
        root=args.dataset_path,
        captions_dir=args.captions_dir,
        generators=args.generators,
        semantics=args.semantics,
        processor_name=args.clip_name,
        max_per_class=args.max_per_class,
        split="val",
        val_frac=args.val_frac,
        seed=args.seed,
        include_uncaptioned=True,   # eval is image-only — use every available image
    )

    sampler = make_balanced_sampler(train_ds)
    train_loader = DataLoader(
        train_ds, batch_size=args.batch_size, sampler=sampler,
        num_workers=args.num_workers, pin_memory=True, drop_last=True,
    )
    val_loader = DataLoader(
        val_ds, batch_size=args.batch_size, shuffle=False,
        num_workers=args.num_workers, pin_memory=True,
    )

    # ── Model ─────────────────────────────────────────────────────────────────
    model = EuclideanAttributionCLIP(
        clip_name=args.clip_name,
        lora_r=args.lora_r,
        lora_alpha=args.lora_alpha,
        embed_dim=args.embed_dim,
        logit_scale_init=args.logit_scale_init,
    ).to(device)

    if torch.cuda.device_count() > 1:
        print(f"Using {torch.cuda.device_count()} GPUs")
        model = nn.DataParallel(model)

    core = model.module if isinstance(model, nn.DataParallel) else model
    core.print_trainable_summary()

    optimizer = torch.optim.AdamW(
        core.trainable_parameters(),
        lr=args.lr,
        weight_decay=args.weight_decay,
    )
    steps_per_epoch = len(train_loader)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=args.num_epochs * steps_per_epoch, eta_min=1e-6
    )
    scaler = GradScaler("cuda")
    ce_loss = PrototypeCELoss()

    # Tokenized anchors stay constant; only the text-encoder weights change.
    tokenizer = CLIPTokenizer.from_pretrained(args.clip_name)
    anchor_tok = tokenizer(anchor_texts, return_tensors="pt", padding="max_length",
                           truncation=True, max_length=77)
    anchor_ids  = anchor_tok["input_ids"].to(device)
    anchor_mask = anchor_tok["attention_mask"].to(device)

    best_balanced = -1.0
    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    # ── Training loop ─────────────────────────────────────────────────────────
    keys = ["acc", "mean_cos_pos", "mean_cos_neg", "logit_scale"]
    for epoch in range(1, args.num_epochs + 1):
        model.train()
        sums = {"loss": 0.0, **{k: 0.0 for k in keys}}
        bar = tqdm(train_loader, desc=f"Epoch {epoch}/{args.num_epochs}")
        for step, batch in enumerate(bar, 1):
            pixel  = batch["pixel_values"].to(device)
            labels = torch.tensor([name_to_idx[g] for g in batch["generator"]],
                                  device=device, dtype=torch.long)

            with autocast("cuda"):
                x_img = model(pixel)
                x_anc = core.encode_text(anchor_ids, anchor_mask)
            # CE is computed in fp32 for stable softmax/log.
            loss, stats = ce_loss(x_img.float(), x_anc.float(), labels, core.logit_scale)

            optimizer.zero_grad()
            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            nn.utils.clip_grad_norm_(core.trainable_parameters(), 1.0)
            scaler.step(optimizer)
            scaler.update()
            scheduler.step()

            sums["loss"] += loss.item()
            for k in keys:
                sums[k] += stats[k].item()

            if step % 25 == 0 or step == steps_per_epoch:
                bar.set_postfix(
                    loss=f"{sums['loss']/step:.3f}",
                    acc=f"{sums['acc']/step:.3f}",
                    cos_pos=f"{sums['mean_cos_pos']/step:.3f}",
                    tau=f"{sums['logit_scale']/step:.1f}",
                )

        avg = {k: v / steps_per_epoch for k, v in sums.items()}
        print(f"\nEpoch {epoch}: train loss={avg['loss']:.4f}  "
              f"train_acc={100*avg['acc']:.1f}%  "
              f"cos_pos={avg['mean_cos_pos']:.3f}  "
              f"cos_neg={avg['mean_cos_neg']:.3f}  "
              f"logit_scale={avg['logit_scale']:.1f}  "
              f"lr={scheduler.get_last_lr()[0]:.2e}")

        # ── Validation ───────────────────────────────────────────────────────
        val = run_validation(core, val_loader, anchor_ids, anchor_mask,
                             class_names, device)
        print(f"  val: overall={100*val['overall_acc']:.1f}%  "
              f"balanced={100*val['balanced_acc']:.1f}%  ({val['total']} samples)")
        for c, a in val["per_class_acc"].items():
            print(f"    {c:10s}: {100*a:5.1f}%")

        # ── Save best checkpoint by balanced val accuracy ────────────────────
        if val["balanced_acc"] > best_balanced:
            best_balanced = val["balanced_acc"]
            torch.save(
                {
                    "lora_state":      core.clip.state_dict(),
                    "projection":      core.projection.state_dict(),
                    "logit_scale":     core.logit_scale.detach().cpu(),
                    "clip_name":       args.clip_name,
                    "lora_r":          args.lora_r,
                    "lora_alpha":      args.lora_alpha,
                    "embed_dim":       args.embed_dim,
                    "geometry":        "euclidean",
                    "class_names":     class_names,
                    "anchor_texts":    anchor_texts,
                    "generators":      args.generators,
                    "semantics":       args.semantics,
                    "val_balanced":    val["balanced_acc"],
                    "epoch":           epoch,
                },
                out_path,
            )
            print(f"  ↳ saved checkpoint (balanced val={100*best_balanced:.1f}%) → {out_path}")

    print(f"\nBest balanced val accuracy: {100*best_balanced:.1f}%  ({out_path})")


if __name__ == "__main__":
    main()
