"""
Stage-1 attribution fine-tuning: CLIP (vision + text) with LoRA.

Each image is paired with an attribution-augmented caption:
  real  → "Real image of {Qwen caption}"
  fake  → "Synthetic image generated by {generator}, showing {Qwen caption}"

The model is trained with symmetric InfoNCE loss so that each image
embedding matches its own caption and not the others in the batch.

After training, image embeddings are close to the text anchor that
describes their origin (e.g. "Synthetic image generated by FLUX"),
enabling zero-shot attribution via cosine similarity.

Usage (single generator, all semantics):
    CUDA_VISIBLE_DEVICES=0,1 python train_attribution.py \\
        --dataset_path  /mnt/data3/rtrebiani/iab_dataset \\
        --captions_dir  /mnt/data3/rtrebiani/iab_captions \\
        --generators    FLUX real \\
        --semantics     COCO cat dog wild FFHQ celebahq bedroom church classroom ImageNet-1k \\
        --output        attribution_checkpoint_FLUX.pt
"""
import argparse
import math
from pathlib import Path

import torch
import torch.nn as nn
from torch.amp import GradScaler, autocast
from torch.utils.data import DataLoader, WeightedRandomSampler
from tqdm import tqdm

from data.iab_clip_dataset import IABCLIPDataset
from models.attribution_clip import AttributionCLIP
from losses.clip_contrastive import clip_contrastive_loss


def parse_args():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--dataset_path",  required=True)
    p.add_argument("--captions_dir",  required=True)
    p.add_argument("--generators",    nargs="+",
                   default=["FLUX", "real"])
    p.add_argument("--semantics",     nargs="+",
                   default=["COCO", "cat", "dog", "wild", "FFHQ", "celebahq",
                             "bedroom", "church", "classroom", "ImageNet-1k"])
    p.add_argument("--output",        default="attribution_checkpoint_FLUX.pt")
    p.add_argument("--clip_name",     default="openai/clip-vit-base-patch32")
    p.add_argument("--lora_r",        type=int,   default=8)
    p.add_argument("--lora_alpha",    type=int,   default=16)
    p.add_argument("--batch_size",    type=int,   default=256)
    p.add_argument("--num_epochs",    type=int,   default=2)
    p.add_argument("--lr",            type=float, default=1e-4)
    p.add_argument("--weight_decay",  type=float, default=0.01)
    p.add_argument("--max_per_class", type=int,   default=None,
                   help="Cap images per (generator, semantic) for quick tests.")
    p.add_argument("--num_workers",   type=int,   default=8)
    return p.parse_args()


def make_balanced_sampler(dataset: IABCLIPDataset) -> WeightedRandomSampler:
    """Equal probability for real and fake samples regardless of class size."""
    is_real = [g == "real" for _, g, _ in dataset.samples]
    n_real = sum(is_real)
    n_fake = len(is_real) - n_real
    if n_real == 0 or n_fake == 0:
        raise RuntimeError(f"Dataset needs both real and fake: {n_real} real, {n_fake} fake")
    weights = [1.0 / n_real if r else 1.0 / n_fake for r in is_real]
    return WeightedRandomSampler(weights, num_samples=len(dataset), replacement=True)


def main():
    args = parse_args()
    device = "cuda" if torch.cuda.is_available() else "cpu"

    # ── Dataset ───────────────────────────────────────────────────────────────
    dataset = IABCLIPDataset(
        root=args.dataset_path,
        captions_dir=args.captions_dir,
        generators=args.generators,
        semantics=args.semantics,
        processor_name=args.clip_name,
        max_per_class=args.max_per_class,
    )
    sampler = make_balanced_sampler(dataset)
    loader = DataLoader(
        dataset,
        batch_size=args.batch_size,
        sampler=sampler,
        num_workers=args.num_workers,
        pin_memory=True,
        drop_last=True,     # keeps batch size fixed for stable InfoNCE
    )

    # ── Model ─────────────────────────────────────────────────────────────────
    model = AttributionCLIP(
        clip_name=args.clip_name,
        lora_r=args.lora_r,
        lora_alpha=args.lora_alpha,
    ).to(device)

    if torch.cuda.device_count() > 1:
        print(f"Using {torch.cuda.device_count()} GPUs")
        model = nn.DataParallel(model)

    core = model.module if isinstance(model, nn.DataParallel) else model
    core.print_trainable_summary()

    optimizer = torch.optim.AdamW(
        core.trainable_parameters(),
        lr=args.lr,
        weight_decay=args.weight_decay,
    )
    steps_per_epoch = len(loader)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=args.num_epochs * steps_per_epoch, eta_min=1e-6
    )
    scaler = GradScaler("cuda")

    # ── Training loop ─────────────────────────────────────────────────────────
    for epoch in range(1, args.num_epochs + 1):
        model.train()
        total_loss = 0.0

        bar = tqdm(loader, desc=f"Epoch {epoch}/{args.num_epochs}")
        for step, batch in enumerate(bar, 1):
            pixel   = batch["pixel_values"].to(device)
            inp_ids = batch["input_ids"].to(device)
            att_msk = batch["attention_mask"].to(device)

            with autocast("cuda"):
                img_emb, txt_emb = model(pixel, inp_ids, att_msk)
                logit_scale = core.logit_scale
                loss = clip_contrastive_loss(img_emb, txt_emb, logit_scale)

            optimizer.zero_grad()
            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            nn.utils.clip_grad_norm_(core.trainable_parameters(), 1.0)
            scaler.step(optimizer)
            scaler.update()
            scheduler.step()
            with torch.no_grad():
                core.clip.base_model.model.logit_scale.clamp_(0, math.log(100))

            total_loss += loss.item()
            if step % 50 == 0 or step == steps_per_epoch:
                avg = total_loss / step
                bar.set_postfix(loss=f"{avg:.4f}",
                                temp=f"{1/logit_scale.item():.4f}")

        avg_loss = total_loss / steps_per_epoch
        print(f"Epoch {epoch}: avg_loss={avg_loss:.4f}  "
              f"logit_scale={core.logit_scale.item():.2f}  "
              f"lr={scheduler.get_last_lr()[0]:.2e}")

    # ── Save ──────────────────────────────────────────────────────────────────
    out_path = Path(args.output)
    torch.save(
        {
            "lora_state":     core.clip.state_dict(),
            "clip_name":      args.clip_name,
            "lora_r":         args.lora_r,
            "lora_alpha":     args.lora_alpha,
            "generators":     args.generators,
            "semantics":      args.semantics,
        },
        out_path,
    )
    print(f"\nCheckpoint saved → {out_path}")


if __name__ == "__main__":
    main()
