"""
Stage-1 attribution fine-tuning with HYPERBOLIC ENTAILMENT CONES.

Each image of class c (e.g. "real" or "FLUX") is pushed inside the entailment
cone of the corresponding fixed text anchor:
  - "A real image"
  - "A synthetic image generated by FLUX"
and outside the cones of all other classes. No content captions are used in
the training objective — only the class anchors. At inference time, an image
is classified by projecting it into Lorentz space and picking the anchor whose
cone it sits in.

Usage:
    CUDA_VISIBLE_DEVICES=0,1,2,3 python train_attribution.py \\
        --dataset_path  $WORK/hyp_fine_tuning/iab_dataset \\
        --captions_dir  $WORK/hyp_fine_tuning/iab_captions \\
        --generators    real FLUX \\
        --semantics     COCO cat dog wild FFHQ celebahq bedroom church classroom ImageNet-1k \\
        --clip_name     openai/clip-vit-large-patch14 \\
        --output        $WORK/hyp_fine_tuning/checkpoints/attribution_FLUX_vitl14.pt
"""
import argparse
import math
import os
from pathlib import Path

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.amp import GradScaler, autocast
from torch.utils.data import DataLoader, WeightedRandomSampler
from tqdm import tqdm
from transformers import CLIPTokenizer

from data.iab_clip_dataset import IABCLIPDataset
from geometry.lorentz import exp_map0, half_aperture, log_map0
from models.attribution_clip import AttributionCLIP
from losses.attribution_loss import EntailmentConeLoss, _pairwise_xi, predict_class
from losses.axis_cone_loss import (AxisConeLoss, axis_cone_q, depth_from_sin_psi,
                                   sin_psi_from_depth)


# Class-anchor text templates. Order matters: this defines the integer labels.
def build_anchors(generators: list[str],
                  prompts_path: str | None = None) -> tuple[list[str], list[str]]:
    """
    Returns (class_names, anchor_texts) in a fixed order.
    class_names[i] is the generator string ("real", "FLUX", ...) used in the dataset;
    anchor_texts[i] is the natural-language anchor encoded by CLIP.

    Default: two templates, so 21 of the 22 anchors differ by a single token and
    CLIP embeds them almost collinearly. `prompts_path` points at a JSON map
    {class_name: sentence} (see data/anchor_prompts_structural.json) whose
    sentences differ in FORM, which spreads the anchors out at init.
    """
    ordered: list[str] = []
    if "real" in generators:
        ordered.append("real")
    for g in generators:
        if g != "real":
            ordered.append(g)

    if prompts_path:
        import json
        with open(prompts_path) as f:
            prompts = json.load(f)
        missing = [c for c in ordered if c not in prompts]
        if missing:
            raise ValueError(f"{prompts_path} has no prompt for {missing}")
        return ordered, [prompts[c] for c in ordered]

    anchor_texts = []
    for c in ordered:
        if c == "real":
            anchor_texts.append("A real image")
        else:
            anchor_texts.append(f"A synthetic image generated by {c}")
    return ordered, anchor_texts


def parse_args():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--dataset_path",   required=True)
    p.add_argument("--captions_dir",   required=True)
    p.add_argument("--generators",     nargs="+", default=["real", "FLUX"])
    p.add_argument("--semantics",      nargs="+",
                   default=["COCO", "cat", "dog", "wild", "FFHQ", "celebahq",
                            "bedroom", "church", "classroom", "ImageNet-1k"])
    p.add_argument("--output",         default="attribution_checkpoint_FLUX.pt")
    p.add_argument("--clip_name",      default="openai/clip-vit-base-patch32")
    p.add_argument("--lora_r",         type=int,   default=8)
    p.add_argument("--lora_alpha",     type=int,   default=16)
    p.add_argument("--lora_target",    type=str,   default=None,
                   help="Regex peft matches (fullmatch) against the base model's module "
                        "names. Default None = q/v of every block in BOTH encoders (72 "
                        "adapters on ViT-L/14). Upper vision blocks only: "
                        r"'vision_model\.encoder\.layers\.(1[2-9]|2[0-3])\.self_attn\.(q|v)_proj' "
                        "(24 adapters), which leaves the lower blocks — where CLIP's word "
                        "knowledge lives — as pretrained.")
    p.add_argument("--hyperbolic_dim", type=int,   default=128)
    p.add_argument("--init_depth",     type=float, default=0.0,
                   help="Target median ‖t_img‖ at init (0 = off, keep --init_scale as is). "
                        "The head is exactly linear in its last layer's weight, so this is "
                        "measured on one batch and applied as a rescale — no guessing at "
                        "--init_scale, whose useful value spans two orders of magnitude "
                        "depending on the backbone. Set it ABOVE the anchors' tangent norm "
                        "(--anchor_init_norm): a cone contains what is deeper than its apex.")
    p.add_argument("--fixed_image_radius", type=float, default=0.0,
                   help="Fix every image's TANGENT norm after the projection head (0 = off). "
                        "This is an ongoing constraint, unlike --init_depth: the head may "
                        "learn directions but cannot contract the image cloud toward the "
                        "origin. Set it above the deepest reachable anchor plus "
                        "--radial_margin.")
    p.add_argument("--radial_margin", type=float, default=0.0,
                   help="Required tangent-radius gap between fixed-radius images and the "
                        "deepest reachable anchor. Validated at startup when "
                        "--fixed_image_radius is enabled.")
    p.add_argument("--anchors_only", action="store_true", default=False,
                   help="Freeze CLIP+LoRA and the projection head after initialisation; "
                        "optimise only free anchors/apertures. Requires a free "
                        "--anchor_init mode.")
    p.add_argument("--init_scale",     type=float, default=0.1,
                   help="Scale on the projection head's last layer, i.e. how DEEP the "
                        "images start. It is not cosmetic with free anchors: an entailment "
                        "cone contains points FARTHER from the origin than its apex, so "
                        "‖x_img‖ must exceed ‖x_anc‖ or every image sits at xi = pi, where "
                        "oxy_angle's acos clamp makes the gradient exactly zero. In 'text' "
                        "mode anchors come out of this same head and the two scales track "
                        "each other; a free anchor rescaled to --anchor_init_norm does not. "
                        "The line 'Image depth at init' printed below reports the ordering.")
    p.add_argument("--curv",           type=float, default=1.0)
    p.add_argument("--min_radius",     type=float, default=0.1)
    p.add_argument("--margin",         type=float, default=0.1)
    p.add_argument("--lambda_neg",     type=float, default=1.0)
    p.add_argument("--lambda_cap_in_class", type=float, default=0.0,
                   help="Hierarchical: weight of caption-in-class-anchor cone term.")
    p.add_argument("--lambda_img_in_cap",   type=float, default=0.0,
                   help="Hierarchical: weight of image-in-own-caption cone term "
                        "(batch negatives).")
    p.add_argument("--no_captions", action="store_true", default=False,
                   help="Pure base attribution loss: forces BOTH caption terms "
                        "(cap_in_class + img_in_cap) to 0 and trains on ALL images (no "
                        "caption requirement) → same sample set as the baselines.")
    p.add_argument("--require_caption", action="store_true", default=False,
                   help="Force training on the captioned-images subset even when the "
                        "caption loss terms are off. Lets the caption on/off ablation run "
                        "on the SAME subset (only the loss varies, not the data).")
    p.add_argument("--anchor_init",
                   choices=["text", "image_centroid", "text_free", "random"],
                   default="text",
                   help="'text' (default): anchors are the class text prompts encoded by "
                        "CLIP at every step (they still move, through the text-encoder LoRA). "
                        "'image_centroid': anchors are FREE parameters in tangent space, "
                        "initialised at the per-class mean of the training image embeddings "
                        "(one forward pass before training) — no text dependency. "
                        "'text_free': free parameters too, but initialised at the encoded "
                        "PROMPTS and allowed to drift only by a learned amount (see "
                        "--anchor_drift_init); at step 0 it is identical to 'text'. "
                        "'random': free parameters from random directions, rescaled to "
                        "--anchor_init_norm. No text encoder, no centroid pre-pass — the "
                        "data decide where the anchors go, from nothing.")
    p.add_argument("--anchor_norm_range", type=float, nargs=2, default=None,
                   metavar=("MIN", "MAX"),
                   help="Hard clamp on the TANGENT norm of the free anchors, applied "
                        "after every optimizer step. psi = asin(2*min_radius/sinh(‖t‖)), "
                        "so the LOWER bound is what keeps the cones from degenerating "
                        "into halfspaces: with min_radius 0.5, ‖t‖=1.0 gives psi 58.3 deg "
                        "and ‖t‖=3.0 gives 5.7 deg. Replaces --lambda_norm (same quantity, "
                        "imposed exactly instead of as a penalty). IGNORED by --loss "
                        "axis, where the aperture is its own parameter (--psi_range) and "
                        "the anchor norm is slaved to it.")
    p.add_argument("--anchor_prompts", type=str, default=None,
                   help="JSON map {class_name: sentence} replacing the two default templates "
                        "(e.g. data/anchor_prompts_structural.json). Used by both 'text' and "
                        "'text_free'. Saved into the checkpoint, and the eval re-encodes THOSE "
                        "sentences — never the defaults.")
    p.add_argument("--anchor_drift_init", type=float, default=0.1,
                   help="'text_free' only: initial value of the single learned scalar s in "
                        "t_c = t0_c + s·δ_c (δ init 0). Small s means the anchors start pinned "
                        "to the prompts and the model decides how far to move them.")
    p.add_argument("--anchor_init_norm", type=float, default=2.0,
                   help="Common tangent-space radius the FREE anchors (image_centroid and "
                        "text_free) are rescaled to at init "
                        "(only their directions carry the information; the radius sets "
                        "the initial cone width, ψ = asin(2·min_radius/‖t‖)). 0 keeps the raw "
                        "scale, which is tiny at init and degenerates every cone to a halfspace.")
    p.add_argument("--anchor_init_cache", type=str, default=None,
                   help="Cache file for the CLIP-space class means. Reused across runs (LoRA is "
                        "zero-init, so the pre-pass output is run-independent) → the ~20 min "
                        "forward pass over the train split happens once.")
    p.add_argument("--train_augment", action="store_true", default=False,
                   help="Random corruption augmentation (JPEG / blur / downsample, see "
                        "data.degradations.random_degradation) on the TRAIN split only. NOTE: "
                        "these are the test-time corruption families → report such a run with an "
                        "asterisk, it is not head-to-head comparable with the baselines.")
    p.add_argument("--aug_policy", choices=["corruption", "omnidfa"], default="corruption",
                   help="Which policy --train_augment applies. 'corruption' (default): the three "
                        "test-time families with continuously sampled parameters. 'omnidfa': "
                        "Table 8 of arXiv 2509.25682 — JPEG q75-95, resize 0.5-2.0, hflip, "
                        "RandAugment (no shear/translate), blur sigma 0.1-2.0. The omnidfa ranges "
                        "cover only DS0.5 of the seven test levels, so its asterisk is much "
                        "weaker than 'corruption''s.")
    p.add_argument("--mixup_alpha",    type=float, default=0.0,
                   help="Manifold mixup in the tangent space at the origin (0 disables it). "
                        "λ~Beta(α,α) mixes the batch with a permutation of itself and the cone "
                        "loss is evaluated twice, weighted λ / 1-λ. Unlike --train_augment this "
                        "shows the model NO corruption, so a run stays head-to-head comparable "
                        "with the baselines: it is the mechanism repmix uses (its ImageNet-C "
                        "perturbation is commented out in dataset_repmix.py) and repmix is the "
                        "only method that holds up under JPEG without seeing degradations.")
    p.add_argument("--mixup_at", choices=["clip", "tangent"], default="clip",
                   help="WHERE the batch is mixed. Mixup only regularises the layers ABOVE the "
                        "mixing point, since they are the ones that receive a mixed vector. "
                        "'clip' mixes the CLIP embedding, so the projection head is trained on "
                        "mixed inputs. 'tangent' mixes after the head, where the only thing left "
                        "is the parameter-free exp_map0 — it reshapes the loss surface but no "
                        "layer ever processes a mixed vector. 'tangent' reproduces the "
                        "attribution_22cls_mixup0.2 checkpoint; 'clip' is the better default.")
    p.add_argument("--blackout_max",   type=float, default=0.0,
                   help="Random pixel blackout on the TRAIN split (0 disables it). Per sample "
                        "λ~U(0, blackout_max) of the pixels are set to BLACK, drawn i.i.d. and "
                        "shared across the 3 channels. Unlike --train_augment none of the three "
                        "test corruption families (JPEG/blur/downsample) is involved → no "
                        "asterisk. Unlike --mixup_alpha the label stays single, so the cone loss "
                        "is called ONCE: no double positive hinge, and λ is a true intensity "
                        "instead of a choice of dominant class.")
    p.add_argument("--lambda_norm",    type=float, default=0.0,
                   help="Weight of the anchor-norm regulariser (0 disables it).")
    p.add_argument("--target_norm",    type=float, default=0.0,
                   help="Target ‖t_anchor‖. With curv=1, ψ ≈ π/8 at ‖t‖≈2.6, π/16 at ‖t‖≈5.")
    p.add_argument("--lambda_axis",    type=float, default=0.0,
                   help="Weight of the AXIS-RAY regulariser (--loss cone only): the "
                        "geodesic distance from each image to the axis ray of its own "
                        "cone. The hinge's gradient is exactly zero once a point is "
                        "inside its cone; this one vanishes only ON the axis, and unlike "
                        "the origin-angle score of --loss axis it reads the RADIUS, so a "
                        "point cannot be scored as on-axis while sitting nowhere near "
                        "the cone. Its apex branch is also the only term here that moves "
                        "an anchor RADIALLY, which is what makes psi (=asin(2K/‖a‖)) a "
                        "learned per-class quantity instead of one that L_norm pins to a "
                        "single value for every class. 0 disables it.")
    p.add_argument("--lambda_hinge",   type=float, default=1.0,
                   help="Scale on the two-term hinge. Set to 0 together with --lambda_ce 1 "
                        "to REPLACE it by cross-entropy rather than mix the two: pure CE "
                        "gives well-conditioned anchors, CE grafted onto a hinge does not "
                        "(Run C ends with pairs at 8.8° AND pairs at 179°).")
    p.add_argument("--norm_mode", choices=["floor", "bilateral"], default="floor",
                   help="'floor' (default, unchanged) penalises only norms BELOW "
                        "--target_norm, so any depth above it is free — which is how Run C's "
                        "anchors drifted to 8.18 with L_norm=0 while sweepwin's sat at 4.11. "
                        "'bilateral' makes it a target, which is what per-level depth needs.")
    p.add_argument("--target_norm_family", type=float, default=0.0,
                   help="Anchor norm for the FAMILY level; must be smaller than --target_norm "
                        "so family cones are wider. With min_radius 0.5: ‖x‖=1.5 → ψ=41.8°, "
                        "‖x‖=5.0 → ψ=11.5°. Equal ψ is exactly why argmin ξ has never differed "
                        "from argmax cos.")
    p.add_argument("--lambda_sep",     type=float, default=0.0,
                   help="Anchor separation on the PROJECTED anchors: at least ψ_c + ψ_c' apart "
                        "+ --separation_margin (the cone-disjointness constraint) and, for "
                        "--loss cone, at most --theta_max apart.")
    p.add_argument("--separation_margin", type=float, default=0.0,
                   help="Degrees of empty angular space required between every cone pair; "
                        "used when --lambda_sep > 0.")
    p.add_argument("--inside_margin", type=float, default=0.0,
                   help="--loss axis only. Degrees by which covered training images must "
                        "sit inside their correct cone wall; applied to the nu-coverage "
                        "constraint, not to the classifier score.")
    p.add_argument("--theta_max",      type=float, default=150.0,
                   help="Degrees. A guard against antipodal pairs, not a shaping term: the "
                        "euclidean model's widest pair is 132.2°, so it stays inert on a "
                        "healthy configuration and fires only on Run C's 179° pathology.")
    p.add_argument("--hierarchy", choices=["none", "hifi", "emergent"], default="none",
                   help="Family level for the nested cones. 'emergent' reads "
                        "--hierarchy_json, written by extract_tree --centroids.")
    p.add_argument("--hierarchy_json", default="data/tree_emergent.json")
    p.add_argument("--lambda_family",  type=float, default=0.0,
                   help="Weight of the two hierarchy terms: model anchor inside its family's "
                        "cone (a hinge — a containment constraint that should stop once met), "
                        "and image inside its family's cone (CE, deliberately NOT a hinge).")
    p.add_argument("--loss", choices=["cone", "axis"], default="cone",
                   help="'cone' (default): the entailment-cone hinge in "
                        "losses/attribution_loss.py, untouched — every checkpoint in the "
                        "method comparison was trained with it. 'axis': the axis-distance "
                        "loss in losses/axis_cone_loss.py — q = ‖x̂ − û_k‖²/‖wall_k‖² = "
                        "(1−cos θ)/(1−cos ψ_k), the squared distance from the cone's axis "
                        "in units of the distance to its wall, so q=1 IS the wall. "
                        "With 'axis' the flags "
                        "--lambda_norm/--target_norm/--lambda_ce/"
                        "--lambda_hinge/--pos_mode/--hierarchy/--init_depth are all "
                        "ignored: that loss has none of those terms and q is invariant "
                        "to the image depth.")
    p.add_argument("--pos_mode", choices=["hinge", "axis"], default="hinge",
                   help="Shape of the positive cone term. 'hinge': max(0, xi-psi), zero "
                        "gradient the moment the point is inside its cone — the measured "
                        "reason the projection head is free to collapse the class geometry "
                        "(centroid ARI 0.253 -> -0.007). 'axis': xi^2, an MSE from the cone "
                        "AXIS, gradient 2*xi everywhere and psi absent, so the loss cannot "
                        "be lowered by widening the cone.")
    p.add_argument("--psi_range", type=float, nargs=2, default=[5.0, 60.0],
                   metavar=("MIN_DEG", "MAX_DEG"),
                   help="--loss axis only. Bounds on the per-class half-aperture, which "
                        "is now a FREE parameter: psi_k = lo + (hi-lo)·sigmoid(raw_k), "
                        "bounded by construction so no clamp is needed. Deriving psi from "
                        "the anchor's depth instead (sin psi = 2K/‖a‖) makes 'widen my "
                        "cone' and 'move toward the origin' the same action, and the "
                        "optimiser always takes that shortcut over rotating the axis: "
                        "measured, psi ran to 65° and its spread across classes collapsed "
                        "from 8.7° to 0.6°, which is exactly when argmin q becomes "
                        "argmax cos. Init is the midpoint of the range.")
    p.add_argument("--nu", type=float, default=0.05,
                   help="--loss axis only. The fraction of a class's OWN samples its cone "
                        "is allowed to leave outside — the slack that stops the cone from "
                        "memorising the training set. With --inside_margin, 'outside' is "
                        "measured against the padded coverage boundary. At stationarity "
                        "mean_i(q_i·1[q_i>1]) = nu, and every counted term has q>1, so nu "
                        "upper-bounds that fraction (the nu-SVM / SVDD property). The "
                        "alternative, putting the wall on the class's RMS radius, sounds "
                        "equivalent and leaves ~42%% of the samples outside their own cone.")
    p.add_argument("--lambda_aperture", type=float, default=1.0,
                   help="--loss axis only. Weight of the log-W aperture term, whose "
                        "equilibrium is controlled by --nu: tight classes get narrow "
                        "cones and ψ varies for a reason that comes from the data. "
                        "Setting it to 0 removes the only downward "
                        "pressure on the aperture — measured: every anchor pins at the "
                        "norm floor and ψ goes uniform, which makes argmin q identical to "
                        "argmax cos.")
    p.add_argument("--neg_samples",    type=int,   default=0,
                   help="Random negatives kept per sample (0 = all K-1, unchanged). This "
                        "does NOT save compute — xi is computed against every anchor anyway "
                        "— it is dropout on the negative term.")
    p.add_argument("--lambda_ce",      type=float, default=0.0,
                   help="Weight of a cross-entropy term on softmax(-ξ/τ) (0 disables it, and "
                        "the loss is then bit-identical to before). The cone hinge saturates: "
                        "once an image is inside its own cone the gradient is zero, and the "
                        "negative term is averaged over K-1 classes so each wrong class weighs "
                        "λ_neg/21. Nothing therefore optimises the RANKING of ξ, which is what "
                        "inference (argmin ξ) actually uses — hence AUC that holds up while "
                        "top-1 collapses under JPEG. The CE penalises probability mass on wrong "
                        "classes in proportion to how close they are. Inference is unchanged: "
                        "argmin ξ is scale-invariant, so τ never reaches the eval.")
    p.add_argument("--ce_tau_init",    type=float, default=1.0,
                   help="Initial temperature of the --lambda_ce term. τ = softplus(param) is "
                        "LEARNED: the exterior angles live in [0, π], so a fixed τ=1 is an "
                        "arbitrary choice of softmax sharpness (same reasoning as CLIP's "
                        "logit_scale).")
    p.add_argument("--batch_size",     type=int,   default=256)
    p.add_argument("--num_epochs",     type=int,   default=10)
    p.add_argument("--lr",             type=float, default=5e-5)
    p.add_argument("--weight_decay",   type=float, default=0.01)
    p.add_argument("--lr_min",         type=float, default=1e-6,
                   help="Floor of the cosine schedule. The default anneals essentially to "
                        "zero, which freezes the geometry mid-transient: in the axis runs "
                        "psi, min-angle and q were all still moving when the last two "
                        "epochs ran at 9.6e-4 and 1e-6, so the final numbers say where the "
                        "clock stopped, not where the equilibrium is. Around lr/10 keeps "
                        "the late epochs doing work.")
    p.add_argument("--lr_schedule", choices=["cosine", "constant"], default="cosine",
                   help="'cosine' (default) anneals from --lr to --lr_min over the run. "
                        "'constant' holds --lr for every step, which is what a "
                        "DIAGNOSTIC run wants: under a decaying schedule a quantity that "
                        "stops moving is indistinguishable from one whose updates went "
                        "to zero, and in the 5-epoch axis runs epoch 1 received 38.7% of "
                        "the total lr budget against epoch 5's 1.3%, so every final "
                        "number recorded where the clock stopped.")
    p.add_argument("--anchor_lr",      type=float, default=None,
                   help="Separate lr for the geometric parameters (anchor tangents, the "
                        "drift scalar, the free aperture). Defaults to --lr, which "
                        "reproduces the single-group behaviour exactly. They also always "
                        "get weight_decay=0: decay on the aperture parameter pulls psi "
                        "toward the middle of --psi_range and, worse, pulls every class "
                        "there together — and a psi with no spread across classes is the "
                        "exact condition under which argmin xi IS argmax cos.")
    p.add_argument("--optimizer", choices=["adamw", "sgd"], default="adamw",
                   help="Default adamw: every checkpoint in the method comparison was "
                        "trained with it, and flipping the default would silently make "
                        "them unreproducible. NOTE --lr does not transfer between the two: "
                        "Adam normalises by the second moment, SGD does not, so an Adam lr "
                        "of 3e-4 barely moves under SGD (start around 1e-2 and re-tune).")
    p.add_argument("--momentum",       type=float, default=0.9,
                   help="SGD momentum (nesterov when > 0). Ignored by adamw.")
    p.add_argument("--val_frac",       type=float, default=0.2)
    p.add_argument("--split_scheme",   choices=["caption", "stratified"], default="caption",
                   help="'stratified' mirrors the comparison baselines' 80/10/10 label split "
                        "(disjoint train/val/test) for a leakage-free fair comparison. "
                        "'caption' is the legacy caption-presence split.")
    p.add_argument("--test_frac",      type=float, default=0.1,
                   help="Held-out test fraction; only used with --split_scheme stratified.")
    p.add_argument("--split_manifest", type=str, default=None,
                   help="JSON split manifest from dump_split_manifest.py. Ours is trained "
                        "ONLY on the manifest's 'train' images (strict data parity with the "
                        "baselines) and never on their val/test → leakage-free, and ours can "
                        "be evaluated on the baselines' EXACT test images (Path 1).")
    p.add_argument("--seed",           type=int,   default=42)
    p.add_argument("--max_per_class",  type=int,   default=None)
    p.add_argument("--num_workers",    type=int,   default=8)
    p.add_argument("--log_every",      type=int,   default=0,
                   help="Append the per-step stats dict to <diag_plot_dir>/stats.csv "
                        "every N steps (0 = off). Costs nothing: psi_min/max_deg, "
                        "sep_min/mean_deg, inside_img and cone_acc are already computed "
                        "every step and then averaged away into the epoch line. The "
                        "anchor collapse in the last axis run went from 78.7 deg to 41.2 "
                        "deg WITHIN epoch 1, so epoch-level logging could not see it.")
    p.add_argument("--snapshot_every", type=int,   default=0,
                   help="Write a Poincare snapshot every N steps as well as per epoch "
                        "(0 = off; requires --diag_plot_dir). The HoroPCA basis is fit "
                        "ONCE before training, so frame 0 is the init configuration and "
                        "every later frame is a cheap projection into the same basis — "
                        "the fit is the expensive half. Uses the current TRAINING batch, "
                        "so a frame costs no extra forward pass.")
    p.add_argument("--diag_plot_dir",  type=str,   default=None,
                   help="Write one Poincare-disk snapshot per epoch here (HoroPCA to 2-D, "
                        "anchors as stars with their cones drawn). Needs the HoroPCA repo — "
                        "see tests/visualize_horopca.py. Reuses the embeddings validation "
                        "already computes, so it costs no extra forward pass.")
    return p.parse_args()


def make_balanced_sampler(dataset: IABCLIPDataset) -> WeightedRandomSampler:
    """K-way balanced sampler: every class sampled with equal probability."""
    from collections import Counter
    counts = Counter(g for _, g, _ in dataset.samples)
    if len(counts) < 2:
        raise RuntimeError(f"Dataset needs at least 2 classes, got: {dict(counts)}")
    if any(n == 0 for n in counts.values()):
        raise RuntimeError(f"Empty class in dataset: {dict(counts)}")
    weights = [1.0 / counts[g] for _, g, _ in dataset.samples]
    print(f"Balanced sampler classes: {dict(counts)}")
    return WeightedRandomSampler(weights, num_samples=len(dataset), replacement=True)


# HiFi-Net level 3, decoded (dataset.py:72-74). The same taxonomy HiFi-Net itself
# uses, so the hierarchy claim is compared on equal terms.
_L3_NAMES = ["commercial", "SD", "diffusers", "DiT", "AR", "real"]


def build_family_anchors(class_names: list[str], hierarchy: str,
                         hierarchy_json: str | None):
    """(family names, family_of per class, one text anchor per family).

    Two trees, both wanted. 'hifi' is the asserted taxonomy; 'emergent' is the one the
    data shows, extracted by comparison.training.scripts.extract_tree from the class
    centroids in LoRA feature space — the only one of three sources that carried signal
    (ARI 0.253, against 0.097 for the projected anchors and 0.027 for the confusion
    matrices).

    Family anchors are text, through the same head as the class anchors, so nothing new
    enters the model beyond the level itself.
    """
    if hierarchy == "hifi":
        from comparison.dataset.ImageAttributionDataset.dataset import _HIFI_HIERARCHY
        tree = {c: _L3_NAMES[_HIFI_HIERARCHY[c][2]] for c in class_names}
    else:
        import json
        with open(hierarchy_json) as f:
            tree = json.load(f)
        missing = [c for c in class_names if c not in tree]
        if missing:
            raise ValueError(f"{hierarchy_json} has no family for {missing}")

    names = sorted({tree[c] for c in class_names})
    family_of = [names.index(tree[c]) for c in class_names]
    texts = ["A real image" if n == "real"
             else f"A synthetic image generated by a model of the {n} family"
             for n in names]
    return names, family_of, texts


@torch.no_grad()
def encode_anchors(model, anchor_texts: list[str], tokenizer, device: str) -> torch.Tensor:
    """Encode the fixed text anchors and return their Lorentz-space coords (K, D)."""
    tok = tokenizer(anchor_texts, return_tensors="pt", padding="max_length",
                    truncation=True, max_length=77)
    x_anc, _ = model.encode_text(tok["input_ids"].to(device),
                                 tok["attention_mask"].to(device))
    return x_anc


@torch.no_grad()
def class_centroids(core, dataset, class_names, args, device,
                    feat_fn=None, cache_path=None) -> torch.Tensor:
    """Per-class mean of the CLIP-space training image embeddings → (K, D_clip).

    Text-free anchor initialisation: one forward pass over the whole train split
    through the vision encoder. LoRA is zero-initialised, so at this point the
    features are exactly the frozen CLIP ones — the result depends only on the
    backbone and the data, which is why it can be cached across runs.

    feat_fn/cache_path override the CLIP-space encoder and the cache file, so a
    second branch (e.g. the spectral one of patch_freq_attribution) can build its
    own anchors with the same machinery.
    """
    name_to_idx = {n: i for i, n in enumerate(class_names)}
    K = len(class_names)
    feat_fn = feat_fn or core._clip_image

    cache_path = cache_path or args.anchor_init_cache
    cache = Path(cache_path) if cache_path else None
    if cache is not None and cache.exists():
        blob = torch.load(cache, map_location="cpu", weights_only=False)
        if blob["class_names"] != class_names:
            raise ValueError(
                f"anchor cache {cache} was built for {blob['class_names']}, "
                f"not for {class_names}")
        print(f"Anchor centroids: loaded from cache {cache}")
        return blob["mean_clip"]

    # Sequential loader: we want the true per-class mean, not the balanced-sampler
    # one. Augmentation off — centroids are always computed on clean images so the
    # clean and augmented runs start from the same anchors.
    was_aug, dataset.train_augment = dataset.train_augment, False
    was_training = core.training
    core.eval()
    loader = DataLoader(dataset, batch_size=args.batch_size, shuffle=False,
                        num_workers=args.num_workers, pin_memory=True)
    clip_dim = core.clip.base_model.model.config.projection_dim
    sums = torch.zeros(K, clip_dim, dtype=torch.float64, device=device)
    counts = torch.zeros(K, dtype=torch.long, device=device)
    for batch in tqdm(loader, desc="anchor centroids"):
        with autocast("cuda"):
            feats = feat_fn(batch["pixel_values"].to(device))
        labels = torch.tensor([name_to_idx[g] for g in batch["generator"]],
                              device=device, dtype=torch.long)
        sums.index_add_(0, labels, feats.double())
        counts.index_add_(0, labels, torch.ones_like(labels))
    dataset.train_augment = was_aug
    core.train(was_training)

    empty = [c for c, n in zip(class_names, counts.tolist()) if n == 0]
    if empty:
        raise RuntimeError(f"No training images for class(es) {empty} — cannot build anchors")
    mean_clip = F.normalize((sums / counts.unsqueeze(1)).float(), dim=-1).cpu()
    print("Anchor centroids (images per class): "
          + ", ".join(f"{c}={n}" for c, n in zip(class_names, counts.tolist())))

    if cache is not None:
        cache.parent.mkdir(parents=True, exist_ok=True)
        tmp = cache.with_suffix(cache.suffix + f".tmp{os.getpid()}")
        torch.save({"class_names": class_names, "mean_clip": mean_clip}, tmp)
        os.replace(tmp, cache)   # atomic: two jobs may race to build the cache
        print(f"Anchor centroids: cached → {cache}")
    return mean_clip


@torch.no_grad()
def run_validation(model_inner, val_loader, x_anc, class_names, device, curv,
                   collect: int = 0, predict=None) -> dict:
    """`predict(x_img, x_anc) -> (B,)` is the decision rule; defaults to argmin xi. The
    axis loss reads a different quantity, and evaluating a model with the wrong rule is
    a failure that shows up as a plausible-looking accuracy, not as an error.

    collect > 0 also returns that many val embeddings (and their labels) for the
    per-epoch snapshot. They are already computed here and thrown away, so it costs no
    extra forward pass — but the quota is PER CLASS: the loader is not shuffled, so
    taking the first `collect` rows gives the first two classes and nothing else, and the
    snapshot then shows a cloud that is not the data."""
    model_inner.eval()

    per_class_correct = {c: 0 for c in class_names}
    per_class_total   = {c: 0 for c in class_names}
    idx_of = {c: i for i, c in enumerate(class_names)}
    emb, emb_lab = [], []
    quota = max(1, collect // len(class_names)) if collect else 0
    taken = {c: 0 for c in class_names}

    for batch in tqdm(val_loader, desc="val", leave=False):
        pixel = batch["pixel_values"].to(device)
        with autocast("cuda"):
            x_img, _ = model_inner.encode_image(pixel)
        if quota and any(n < quota for n in taken.values()):
            keep = []
            for j, g in enumerate(batch["generator"]):
                if taken[g] < quota:
                    taken[g] += 1
                    keep.append(j)
            if keep:
                emb.append(x_img[keep].float().cpu())
                emb_lab.extend(idx_of[batch["generator"][j]] for j in keep)
        pred_idx = (predict(x_img, x_anc) if predict is not None
                    else predict_class(x_img, x_anc, curv=curv))
        pred_names = [class_names[i] for i in pred_idx.tolist()]
        for pred, gt in zip(pred_names, batch["generator"]):
            per_class_total[gt] += 1
            per_class_correct[gt] += int(pred == gt)

    total = sum(per_class_total.values())
    correct = sum(per_class_correct.values())
    per_class_acc = {
        c: (per_class_correct[c] / per_class_total[c]) if per_class_total[c] > 0 else 0.0
        for c in class_names
    }
    balanced = sum(per_class_acc.values()) / len(class_names)
    return {
        "overall_acc":   correct / total if total else 0.0,
        "balanced_acc":  balanced,
        "per_class_acc": per_class_acc,
        "total":         total,
        "emb":           torch.cat(emb).numpy() if emb else None,
        "emb_labels":    emb_lab,
    }


def main():
    args = parse_args()
    if min(args.fixed_image_radius, args.radial_margin, args.separation_margin,
           args.inside_margin) < 0:
        raise ValueError("radius and angular margins must be non-negative")
    if args.fixed_image_radius > 0 and args.init_depth > 0:
        raise ValueError("Use --fixed_image_radius or --init_depth, not both")
    if args.anchors_only and args.anchor_init == "text":
        raise ValueError("--anchors_only requires free anchors: random, image_centroid, "
                         "or text_free")
    if args.loss == "axis" and not (0 < args.psi_range[0] <= args.psi_range[1] < 90):
        raise ValueError("--psi_range must satisfy 0 < MIN <= MAX < 90 degrees")
    if args.loss == "axis" and args.inside_margin >= args.psi_range[1]:
        raise ValueError("--inside_margin must be smaller than the maximum --psi_range")
    if args.fixed_image_radius > 0:
        if args.anchor_init not in ("random", "image_centroid"):
            raise ValueError("--fixed_image_radius needs random or image_centroid anchors "
                             "whose depth is bounded")
        if args.loss == "axis":
            rc = args.curv ** 0.5
            min_psi = math.radians(args.psi_range[0])
            max_anchor_radius = math.asinh(
                rc * 2.0 * args.min_radius / math.sin(min_psi)) / rc
        elif args.anchor_norm_range:
            max_anchor_radius = args.anchor_norm_range[1]
        else:
            raise ValueError("--fixed_image_radius with --loss cone also needs "
                             "--anchor_norm_range to bound anchor depth")
        required = max_anchor_radius + args.radial_margin
        if args.fixed_image_radius < required:
            raise ValueError(
                f"--fixed_image_radius {args.fixed_image_radius:g} must be at least "
                f"{required:.3f}: deepest anchor {max_anchor_radius:.3f} + "
                f"radial margin {args.radial_margin:g}")
    if args.no_captions:
        args.lambda_cap_in_class = 0.0
        args.lambda_img_in_cap = 0.0
    device = "cuda" if torch.cuda.is_available() else "cpu"
    # Covers the projection-head init and the balanced sampler's draw order (the
    # dataset splits already seed their own RNG). NOT bit-exact: GPU reduction
    # order still varies, so two seeded runs agree closely, not to the last digit.
    torch.manual_seed(args.seed)
    print(f"Seed: {args.seed}")

    class_names, anchor_texts = build_anchors(args.generators, args.anchor_prompts)
    name_to_idx = {n: i for i, n in enumerate(class_names)}
    if args.anchor_init != "text" and (args.lambda_cap_in_class > 0
                                       or args.lambda_img_in_cap > 0):
        # Free anchors take the text encoder out of the objective (it is used at most
        # once, at init), so the caption terms have no anchor that keeps moving with
        # the captions. Same reasoning for both free modes.
        raise ValueError(f"--anchor_init {args.anchor_init} makes the anchors free "
                         f"parameters; the caption terms have no class anchor to attach "
                         f"to. Use --no_captions.")
    if args.anchor_init == "image_centroid":
        print(f"Class anchors: image centroids (text-free), {len(class_names)} classes")
        for i, c in enumerate(class_names):
            print(f"  [{i}] {c}")
    else:
        src = args.anchor_prompts or "default templates"
        print(f"Class anchors ({args.anchor_init}, from {src}):")
        for i, (c, t) in enumerate(zip(class_names, anchor_texts)):
            print(f"  [{i}] {c:14s} → \"{t}\"")

    # ── Split manifest (Path 1: strict data parity + leakage-free vs baselines) ──
    # With a manifest: train on ALL harness-train images and validate on the harness
    # VAL split — no internal re-split (avoids the double val carve that shrank the
    # train set) and no data loss. require_caption follows whether any caption term
    # is active. Without a manifest: legacy caption-based split.
    use_caps = (args.lambda_cap_in_class > 0 or args.lambda_img_in_cap > 0)
    if args.loss == "axis" and use_caps:
        raise ValueError("--loss axis has no caption terms; it scores images against "
                         "class cones only. Drop --lambda_cap_in_class/--lambda_img_in_cap "
                         "or use --loss cone.")
    # Training set membership: captioned-only if any caption term is active OR if
    # --require_caption forces it (caption on/off ablation on the same subset).
    # Decoupled from use_caps so caption-OFF can share the captioned subset.
    req_cap = use_caps or args.require_caption
    train_include = val_include = None
    if args.split_manifest:
        import json
        with open(args.split_manifest) as f:
            man = json.load(f)
        train_include = set(man["train"])
        val_include = set(man["val"])
        print(f"Split manifest: {len(train_include)} train + {len(val_include)} val images "
              f"(require_caption={req_cap}; harness val used for model selection)")

    # ── Datasets ──────────────────────────────────────────────────────────────
    print("\n=== Train split ===")
    if train_include is not None:
        train_ds = IABCLIPDataset(
            root=args.dataset_path, captions_dir=args.captions_dir,
            generators=args.generators, semantics=args.semantics,
            processor_name=args.clip_name, max_per_class=args.max_per_class,
            split="all", seed=args.seed,
            include_paths=train_include, require_caption=req_cap,
        )
        print("\n=== Val split (harness val) ===")
        val_ds = IABCLIPDataset(
            root=args.dataset_path, captions_dir=args.captions_dir,
            generators=args.generators, semantics=args.semantics,
            processor_name=args.clip_name, max_per_class=args.max_per_class,
            split="all", seed=args.seed,
            include_paths=val_include, require_caption=False, include_uncaptioned=True,
        )
    else:
        train_ds = IABCLIPDataset(
            root=args.dataset_path, captions_dir=args.captions_dir,
            generators=args.generators, semantics=args.semantics,
            processor_name=args.clip_name, max_per_class=args.max_per_class,
            split="train", val_frac=args.val_frac, seed=args.seed,
            split_scheme=args.split_scheme, test_frac=args.test_frac,
            require_caption=req_cap,
        )
        print("\n=== Val split ===")
        val_ds = IABCLIPDataset(
            root=args.dataset_path, captions_dir=args.captions_dir,
            generators=args.generators, semantics=args.semantics,
            processor_name=args.clip_name, max_per_class=args.max_per_class,
            split="val", val_frac=args.val_frac, seed=args.seed,
            include_uncaptioned=True, split_scheme=args.split_scheme, test_frac=args.test_frac,
            require_caption=use_caps,
        )

    # Augmentation on the train split only: the val split stays clean so model
    # selection is not measured under corruption.
    train_ds.train_augment = args.train_augment
    train_ds.aug_policy = args.aug_policy
    if args.train_augment:
        what = ("random JPEG / blur / downsample" if args.aug_policy == "corruption"
                else "OmniDFA Table 8 (JPEG 75-95 / resize / hflip / RandAugment / blur)")
        print(f"Train-time augmentation: ON  policy={args.aug_policy}  ({what}) — "
              "results are NOT head-to-head comparable with the baselines.")

    # "Black" AFTER the CLIP normalisation is (0 − mean)/std ≈ −1.79, not 0 — zeroing
    # the normalised tensor would paint the CLIP mean colour (grey) instead.
    black = -(torch.tensor(train_ds.processor.image_mean, device=device)
              / torch.tensor(train_ds.processor.image_std, device=device)).view(1, 3, 1, 1)
    if args.blackout_max > 0:
        print(f"Blackout: λ~U(0,{args.blackout_max}) per sample")

    sampler = make_balanced_sampler(train_ds)
    train_loader = DataLoader(
        train_ds, batch_size=args.batch_size, sampler=sampler,
        num_workers=args.num_workers, pin_memory=True, drop_last=True,
    )
    val_loader = DataLoader(
        val_ds, batch_size=args.batch_size, shuffle=False,
        num_workers=args.num_workers, pin_memory=True,
    )

    # ── Model ─────────────────────────────────────────────────────────────────
    model = AttributionCLIP(
        clip_name=args.clip_name,
        lora_r=args.lora_r,
        lora_alpha=args.lora_alpha,
        hyperbolic_dim=args.hyperbolic_dim,
        curv=args.curv,
        lora_target=args.lora_target,
        init_scale=args.init_scale,
        image_radius=args.fixed_image_radius,
    ).to(device)

    # ── Anchors ───────────────────────────────────────────────────────────────
    # Two free-anchor modes, both producing a tangent-space starting point t0 whose
    # DIRECTIONS carry the information and whose radius is reset to a common value
    # (the raw radius out of the projection head is ~0.1 because of init_scale, and
    # that degenerates every cone into a halfspace):
    #   image_centroid — t0 = per-class mean of the training image embeddings, from
    #                    one pre-pass over the train split (single GPU, before the
    #                    DataParallel wrap). No text at all.
    #   random         — t0 = random directions. The anchors carry no prior at all;
    #                    where they end up is entirely what the loss put there.
    #   text_free      — t0 = the encoded class PROMPTS. Same starting point as plain
    #                    'text' mode up to the common rescale, but from there the
    #                    anchors may drift by t = t0 + softplus(s)·δ, with δ init 0
    #                    and s a SINGLE learned scalar: the model decides how far to
    #                    move away from the prompts.
    anchor_tangent = None                      # image_centroid: the parameter itself
    anchor_t0 = anchor_delta = anchor_drift = None    # text_free

    # Tokenized anchors stay constant; only the text-encoder weights change.
    tokenizer = CLIPTokenizer.from_pretrained(args.clip_name)
    anchor_tok = tokenizer(anchor_texts, return_tensors="pt", padding="max_length",
                           truncation=True, max_length=77)
    anchor_ids  = anchor_tok["input_ids"].to(device)
    anchor_mask = anchor_tok["attention_mask"].to(device)

    fam_ids = fam_mask = family_of = None
    family_names: list[str] = []
    if args.hierarchy != "none":
        family_names, fam_idx, fam_texts = build_family_anchors(
            class_names, args.hierarchy, args.hierarchy_json)
        fam_tok = tokenizer(fam_texts, return_tensors="pt", padding="max_length",
                            truncation=True, max_length=77)
        fam_ids  = fam_tok["input_ids"].to(device)
        fam_mask = fam_tok["attention_mask"].to(device)
        family_of = torch.tensor(fam_idx, dtype=torch.long, device=device)
        print(f"Hierarchy '{args.hierarchy}': {len(family_names)} families")
        for f, name in enumerate(family_names):
            members = [c for c, i in zip(class_names, fam_idx) if i == f]
            print(f"  {name:16s} <- " + ", ".join(members))

    if args.anchor_init != "text":
        with torch.no_grad():
            if args.anchor_init == "random":
                # Directions from nothing: no text encoder, no centroid pre-pass.
                # In 128 dimensions random directions are near-orthogonal, so the
                # spread check below should report mean angle ~90 deg.
                g = torch.Generator().manual_seed(args.seed)
                t0 = torch.randn(len(class_names), args.hyperbolic_dim,
                                 generator=g).to(device)
            elif args.anchor_init == "image_centroid":
                t0 = model.projection(
                    class_centroids(model, train_ds, class_names, args, device).to(device))
            else:
                _, t0 = model.encode_text(anchor_ids, anchor_mask)
            if args.anchor_init_norm > 0:
                t0 = F.normalize(t0, dim=-1) * args.anchor_init_norm
            t0 = t0.detach().float()

        if args.anchor_init in ("image_centroid", "random"):
            anchor_tangent = nn.Parameter(t0)
        else:
            anchor_t0 = t0                                        # fixed reference
            anchor_delta = nn.Parameter(torch.zeros_like(t0))
            # s = softplus(raw): positive, unconstrained, one scalar for all classes.
            anchor_drift = nn.Parameter(
                torch.tensor(float(args.anchor_drift_init)).expm1().clamp(min=1e-6).log())

        with torch.no_grad():
            psi0 = half_aperture(exp_map0(t0, curv=args.curv),
                                 curv=args.curv, min_radius=args.min_radius)
            # Angular spread at init: if the anchors sit closer together than 2ψ their
            # cones overlap and the free parameters can collapse winner-take-all (this
            # is what killed mid-6.0 in the centroid run).
            d = F.normalize(t0, dim=-1)
            cos = (d @ d.T).clamp(-1, 1)
            iu = torch.triu_indices(len(class_names), len(class_names), offset=1)
            ang = torch.arccos(cos[iu[0], iu[1]])     # off-diagonal pairs only
        # Degrees, to match every epoch line — this used to print radians next to a
        # min∠ of 1.374, which reads as a small number and is in fact 78.7°. And for
        # --loss axis the psi below is NOT the one in force: the aperture there is a free
        # parameter and the block after this one reassigns ‖t‖ to the depth it implies,
        # so half_aperture(t0) reports the pre-slaving value (16.0° where the run
        # actually starts at 32.5°). Say which is which instead of printing the stale one.
        psi_lo_d, psi_hi_d = args.psi_range
        psi_txt = (f"ψ={0.5 * (psi_lo_d + psi_hi_d):.1f}° (free, mid --psi_range)"
                   if args.loss == "axis"
                   else f"ψ={math.degrees(psi0.mean()):.1f}° (=asin(2K/‖a‖))")
        print(f"Anchor init ({args.anchor_init}): ‖t‖={t0.norm(dim=-1).mean():.2f}  "
              f"{psi_txt}  min∠={math.degrees(ang.min()):.1f}°  "
              f"mean∠={math.degrees(ang.mean()):.1f}°  (K={len(class_names)})")
        if args.loss != "axis" and ang.min() < 2 * psi0.mean():
            print(f"  ⚠️  closest anchor pair is inside "
                  f"2ψ={math.degrees(2 * psi0.mean()):.1f}° — those cones overlap at init")
        if anchor_drift is not None:
            print(f"  drift scale s={F.softplus(anchor_drift).item():.3f} (learned)")

    # ── Aperture, decoupled from the anchor's depth (--loss axis) ────────────
    # psi is its own parameter so that rotating the axis and widening the cone are two
    # different moves. sigmoid keeps it inside --psi_range with no projection step, and
    # the anchor tangent's norm is then slaved to it after every optimizer step, so the
    # anchor still sits at the depth its aperture implies (2K/sin psi) for the plots and
    # for the checkpoint.
    anchor_psi_raw = None
    psi_lo, psi_hi = (math.radians(v) for v in args.psi_range)
    if args.loss == "axis":
        anchor_psi_raw = nn.Parameter(torch.zeros(len(class_names), device=device))
        if anchor_tangent is not None:
            # Slave the norm once here too, so the init report and the first snapshot
            # show the depth the aperture implies rather than --anchor_init_norm.
            with torch.no_grad():
                rc = args.curv ** 0.5
                sp0 = torch.sin(psi_lo + (psi_hi - psi_lo)
                                * torch.sigmoid(anchor_psi_raw))
                want = torch.asinh(rc * depth_from_sin_psi(sp0, args.min_radius)) / rc
                anchor_tangent.mul_(
                    want.unsqueeze(1)
                    / anchor_tangent.norm(dim=-1, keepdim=True).clamp_min(1e-8))

    def sin_psi_now():
        """(K,) sine of each half-aperture, or None outside the axis loss."""
        if anchor_psi_raw is None:
            return None
        return torch.sin(psi_lo + (psi_hi - psi_lo) * torch.sigmoid(anchor_psi_raw))

    def anchor_tangent_now():
        """Current tangent anchors (K, D_hyp), or None in plain 'text' mode."""
        if anchor_delta is not None:
            return anchor_t0 + F.softplus(anchor_drift) * anchor_delta
        return anchor_tangent

    # ── Depth ordering at init ───────────────────────────────────────────────
    # An entailment cone contains the points FARTHER from the origin than its apex, so
    # the images have to be deeper than the anchors. If they are not, every xi sits at
    # pi and oxy_angle's acos clamp makes the gradient exactly zero — the run reports a
    # perfectly constant loss and chance accuracy at every learning rate.
    model.eval()
    with torch.no_grad():
        probe = next(iter(train_loader))["pixel_values"][:64].to(device)
        if args.init_depth > 0:
            # t = W2·GELU(W1·x) + b2 is exactly linear in (W2, b2), so one measurement
            # gives the exact rescale. In 'text' mode this moves the anchors too — they
            # come out of the same head — which is the point: the two scales must track.
            cur = model.encode_image(probe)[1].norm(dim=-1).median().item()
            k = args.init_depth / max(cur, 1e-12)
            model.projection[-1].weight.mul_(k)
            model.projection[-1].bias.mul_(k)
            print(f"Head calibrated for --init_depth: ‖t_img‖ {cur:.4f} → "
                  f"{args.init_depth:.2f} (last layer ×{k:.1f})")
        x_probe, t_probe = model.encode_image(probe)
        t_now = anchor_tangent_now()
        x_anc0 = (exp_map0(t_now.float(), curv=args.curv) if t_now is not None
                  else model.encode_text(anchor_ids, anchor_mask)[0])
        if args.loss == "axis":
            psi0 = torch.arcsin(sin_psi_now())
            q0 = axis_cone_q(x_probe, x_anc0, sin_psi_now())
        else:
            psi0 = half_aperture(x_anc0, curv=args.curv, min_radius=args.min_radius)
            xi0 = _pairwise_xi(x_anc0, x_probe, curv=args.curv)
            pinned = (xi0 > math.pi - 5e-3).float().mean().item()
    if args.anchors_only:
        model.requires_grad_(False)
        model.eval()
        print("Anchors-only: CLIP+LoRA and projection head frozen in eval mode")
    else:
        model.train()
    t_img = t_probe.norm(dim=-1).median().item()
    x_img = x_probe.norm(dim=-1).median().item()
    x_anc_n = x_anc0.norm(dim=-1).median().item()
    x_anc_max = x_anc0.norm(dim=-1).max().item()
    print(f"Image depth at init: ‖t_img‖={t_img:.3f} ‖x_img‖={x_img:.3f}  vs  "
          f"‖x_anc‖={x_anc_n:.3f} (max {x_anc_max:.3f})")
    if args.loss == "axis":
        # q is invariant to the image depth, so there is no ordering to get wrong here;
        # what matters is that psi is non-degenerate and q starts well above 1 (outside
        # every cone) rather than at 0 (already collapsed).
        print(f"  q(image, cone) median {q0.median().item():.3f}  "
              f"min {q0.min().item():.3f}  "
              f"ψ∈[{math.degrees(psi0.min()):.1f},{math.degrees(psi0.max()):.1f}]°  "
              f"(q=1 is the cone wall)")
    else:
        print(f"  ξ(anchor→image) median {xi0.median().item():.3f} rad "
              f"({math.degrees(xi0.median().item()):.1f}°)  ψ={psi0.median().item():.3f}  "
              f"{100 * pinned:.0f}% pinned at π   (images must be DEEPER than anchors)")
        # HARD failure, not a warning. This is the exact configuration the last axis run
        # trained in for five epochs — ‖x_img‖=0.009 against ‖x_anc‖=1.861, images ~200x
        # SHALLOWER than their anchors, so no image was inside any cone at any point —
        # and nothing in the epoch line said so. The cone rule cannot be evaluated at all
        # in that regime, so refuse to start rather than produce another unreadable run.
        if x_img <= x_anc_max:
            want = 1.5 * math.asinh(x_anc_max)
            raise ValueError(
                f"containment INVERTED: median image depth ‖x_img‖={x_img:.4f} is not "
                f"above the DEEPEST anchor ‖x_anc‖={x_anc_max:.4f}. An entailment cone "
                f"holds the points farther from the origin than its apex, so every ξ "
                f"sits at π and oxy_angle's acos clamp makes the gradient exactly zero "
                f"— no learning rate moves it.\n"
                f"    Fix: --init_depth {want:.2f}  (1.5x the deepest anchor's tangent "
                f"norm, giving ‖x_img‖≈{math.sinh(want):.1f})."
            )
        if pinned > 0.05:
            print(f"  ⚠️  {100 * pinned:.0f}% of the ξ matrix is pinned at π even though "
                  f"the depth ordering is right — check the anchor spread.")

    if torch.cuda.device_count() > 1:
        print(f"Using {torch.cuda.device_count()} GPUs")
        model = nn.DataParallel(model)

    core = model.module if isinstance(model, nn.DataParallel) else model
    core.print_trainable_summary()

    # Built before the optimizer: with --lambda_ce it owns a learned temperature that
    # has to be in the parameter list.
    if args.loss == "axis":
        cone_loss = AxisConeLoss(
            min_radius=args.min_radius, lambda_neg=args.lambda_neg,
            neg_samples=args.neg_samples, lambda_aperture=args.lambda_aperture,
            nu=args.nu, lambda_sep=args.lambda_sep,
            separation_margin=args.separation_margin,
            inside_margin=args.inside_margin,
        ).to(device)
        val_predict = lambda xi_, xa_: axis_cone_q(
            xi_, xa_, sin_psi_now().detach()).argmin(1)
    else:
        val_predict = None
        cone_loss = EntailmentConeLoss(
            curv=args.curv, min_radius=args.min_radius,
            margin=args.margin, lambda_neg=args.lambda_neg,
            lambda_cap_in_class=args.lambda_cap_in_class,
            lambda_img_in_cap=args.lambda_img_in_cap,
            lambda_norm=args.lambda_norm, target_norm=args.target_norm,
            lambda_axis=args.lambda_axis,
            lambda_ce=args.lambda_ce, ce_tau_init=args.ce_tau_init,
            lambda_hinge=args.lambda_hinge, norm_mode=args.norm_mode,
            target_norm_family=args.target_norm_family,
            lambda_sep=args.lambda_sep, separation_margin=args.separation_margin,
            theta_max=args.theta_max,
            lambda_family=args.lambda_family, family_of=family_of,
            pos_mode=args.pos_mode, neg_samples=args.neg_samples,
        ).to(device)

    # Two parameter groups, because the geometric parameters and the backbone have
    # nothing in common numerically: 22 anchor directions and K apertures against 1.5M
    # LoRA weights, with gradients on entirely different scales. Sharing one lr and one
    # weight decay across them is a default, not a decision — and the decay in
    # particular is actively wrong on the aperture (see --anchor_lr).
    backbone = core.trainable_parameters() + list(cone_loss.parameters())
    geometric = [p for p in (anchor_tangent, anchor_delta, anchor_drift, anchor_psi_raw)
                 if p is not None]
    anchor_lr = args.lr if args.anchor_lr is None else args.anchor_lr
    groups = []
    if backbone:
        groups.append({"params": backbone, "lr": args.lr,
                       "weight_decay": args.weight_decay})
    if geometric:
        groups.append({"params": geometric, "lr": anchor_lr, "weight_decay": 0.0})
    if not groups:
        raise ValueError("No trainable parameters: use a free --anchor_init mode or "
                         "disable --anchors_only")
    if args.optimizer == "sgd":
        optimizer = torch.optim.SGD(
            groups,
            lr=args.lr,
            momentum=args.momentum,
            nesterov=args.momentum > 0,
            weight_decay=args.weight_decay,
        )
    else:
        optimizer = torch.optim.AdamW(
            groups,
            lr=args.lr,
            weight_decay=args.weight_decay,
        )
    print(f"Optimizer: {args.optimizer}"
          + (f" (momentum {args.momentum}, nesterov)" if args.optimizer == "sgd" else "")
          + f"  lr={args.lr}  weight_decay={args.weight_decay}"
          + (f"  |  {len(geometric)} geometric tensors at lr={anchor_lr} wd=0"
             if geometric else ""))
    steps_per_epoch = len(train_loader)
    if args.lr_schedule == "constant":
        # A no-op scheduler rather than dropping the call site: scheduler.step() stays
        # where it is, and get_last_lr() keeps working for the epoch line.
        scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, lambda _: 1.0)
        print(f"LR schedule: constant at {args.lr} for all "
              f"{args.num_epochs * steps_per_epoch} steps")
    else:
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
            optimizer, T_max=args.num_epochs * steps_per_epoch, eta_min=args.lr_min
        )
        print(f"LR schedule: cosine {args.lr} → {args.lr_min}")
    scaler = GradScaler("cuda")
    if args.lambda_ce > 0:
        print(f"CE ranking term: λ_ce={args.lambda_ce}  τ_init={args.ce_tau_init} (learned)")
    if use_caps:
        print(f"Hierarchical mode: λ_cap_in_class={args.lambda_cap_in_class} "
              f"λ_img_in_cap={args.lambda_img_in_cap}")
    else:
        print("Base attribution loss only (no caption terms).")

    if args.mixup_alpha > 0:
        if use_caps:
            raise ValueError("--mixup_alpha needs --no_captions: mixing images but not their "
                             "captions makes L_img_in_cap meaningless.")
        mixup_beta = torch.distributions.Beta(args.mixup_alpha, args.mixup_alpha)
        print(f"Mixup: α={args.mixup_alpha} at '{args.mixup_at}'")
    mix_at_clip = args.mixup_alpha > 0 and args.mixup_at == "clip"

    # Resolved here, not inside the loop: a missing HoroPCA clone should kill the job
    # in the first second, not after the first epoch of training. The import alone is
    # not enough — HoroPCA is located lazily, so probe it now.
    plot_epoch_snapshot = None
    diag_state = None
    snap_every = 0
    if args.diag_plot_dir:
        from tests.visualize_horopca import plot_epoch_snapshot, _load_horopca
        _load_horopca()
        Path(args.diag_plot_dir).mkdir(parents=True, exist_ok=True)
        snap_every = args.snapshot_every
        print(f"Per-epoch Poincare snapshots → {args.diag_plot_dir}"
              + (f" (+ every {snap_every} steps)" if snap_every else ""))

    def snap_psi():
        """(K,) half-apertures for the snapshot, in the parameterisation actually in
        force. Under --loss axis psi is a free parameter, so recomputing it from the
        anchor norm inside the plotter reports a value the model does not have."""
        return (torch.arcsin(sin_psi_now()).detach().float().cpu().numpy()
                if args.loss == "axis" else None)

    # ── Step-level trace ─────────────────────────────────────────────────────
    stat_csv = None
    stat_csv_keys: list[str] = []
    if args.log_every > 0:
        if not args.diag_plot_dir:
            raise ValueError("--log_every needs --diag_plot_dir to write stats.csv into")
        stat_csv = open(Path(args.diag_plot_dir) / "stats.csv", "w", encoding="utf-8")
        print(f"Step-level stats every {args.log_every} steps → "
              f"{Path(args.diag_plot_dir) / 'stats.csv'}")

    best_balanced = -1.0
    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    # ── Training loop ─────────────────────────────────────────────────────────
    axis = args.loss == "axis"
    if axis:
        base_keys = ["loss_pos", "loss_neg", "loss_ap", "q_pos", "inside_img",
                     "viol_mass", "cone_acc", "loss_sep", "sep_overlap",
                     "psi_min_deg", "psi_deg", "psi_max_deg",
                     "sep_min_deg", "sep_mean_deg", "anc_norm"]
    else:
        base_keys = ["loss_img_in_cls", "loss_pos", "loss_neg", "xi_sat",
                     "psi_min_deg", "psi_max_deg",
                     "sep_min_deg", "sep_mean_deg", "sep_overlap",
                     "loss_cap_in_cls", "loss_img_in_cap", "loss_norm",
                     "cone_acc", "inside_img", "mean_psi_anc", "mean_xi_img_anc",
                     "mean_anc_norm"]
    cap_keys  = ["inside_cap", "inside_img_cap", "mean_psi_cap",
                 "mean_xi_cap_anc", "mean_xi_img_cap", "mean_cap_norm"]
    ce_keys   = ["loss_ce", "ce_tau"] if args.lambda_ce > 0 and not axis else []
    axreg_keys = (["loss_axis", "frac_shallow"]
                  if args.lambda_axis > 0 and not axis else [])
    sep_keys  = (["loss_sep", "sep_max_deg"]
                 if args.lambda_sep > 0 and not axis else [])
    fam_keys  = (["loss_fam_anc", "loss_fam_img", "inside_family", "family_acc",
                  "mean_psi_fam", "fam_tau"]
                 if args.lambda_family > 0 and args.hierarchy != "none" and not axis
                 else [])

    # Everything the loss already emits per step. No extra computation: these are
    # computed inside the loss every step and, until now, averaged away into one line.
    stat_csv_keys = base_keys + ce_keys + axreg_keys + sep_keys + fam_keys
    if use_caps:
        stat_csv_keys = stat_csv_keys + cap_keys

    # Frame 0, fit BEFORE any optimiser step: the basis and the Frechet isometry are
    # reused for every later frame (the fit is the expensive half of HoroPCA), and the
    # configuration the anchors start from is the baseline the run is read against —
    # random directions in 128-d give min∠ ≈ 78.7°, mean∠ ≈ 89.9°.
    if snap_every and plot_epoch_snapshot is not None:
        model.eval()
        with torch.no_grad():
            # Several batches, not one: this is the ONLY fit in the run — every later
            # frame reuses this basis, which is what makes them comparable — so its
            # quality sets the quality of the whole sequence. plot_epoch_snapshot
            # subsamples to max_points=1500 for the fit, so that is the target.
            e0, l0 = [], []
            for probe0 in train_loader:
                e0.append(core.encode_image(probe0["pixel_values"].to(device))[0]
                          .float().cpu())
                l0.extend(name_to_idx[g] for g in probe0["generator"])
                if sum(t.shape[0] for t in e0) >= 1500:
                    break
            t_now0 = anchor_tangent_now()
            xa0 = (exp_map0(t_now0.float(), curv=args.curv) if t_now0 is not None
                   else core.encode_text(anchor_ids, anchor_mask)[0])
            diag_state = plot_epoch_snapshot(
                torch.cat(e0).numpy(), l0, xa0, class_names,
                Path(args.diag_plot_dir) / "step_0000000.png",
                curv=args.curv, min_radius=args.min_radius,
                psi=snap_psi(), state=None, seed=args.seed, title="init (step 0)")
        if not args.anchors_only:
            model.train()

    global_step = 0
    for epoch in range(1, args.num_epochs + 1):
        if args.anchors_only:
            model.eval()
        else:
            model.train()
        sums = {"loss": 0.0,
                **{k: 0.0 for k in
                   base_keys + ce_keys + axreg_keys + sep_keys + fam_keys}}
        if use_caps:
            sums.update({k: 0.0 for k in cap_keys})
        bar = tqdm(train_loader, desc=f"Epoch {epoch}/{args.num_epochs}")
        for step, batch in enumerate(bar, 1):
            global_step += 1
            pixel    = batch["pixel_values"].to(device)
            cap_ids  = batch["input_ids"].to(device)        # already tokenized augmented caption
            cap_mask = batch["attention_mask"].to(device)
            labels   = torch.tensor([name_to_idx[g] for g in batch["generator"]],
                                    device=device, dtype=torch.long)

            if args.blackout_max > 0:
                # One λ per sample, so a batch carries the whole spectrum of occlusion.
                # The mask is (B,1,H,W) → broadcast over the channels, i.e. the whole
                # pixel goes black. Applied on the full batch, before the DataParallel
                # scatter. The label is untouched: the cone loss below runs once.
                lam  = torch.rand(pixel.size(0), 1, 1, 1, device=device) * args.blackout_max
                mask = torch.rand(pixel.size(0), 1, *pixel.shape[-2:], device=device) < lam
                pixel = torch.where(mask, black.to(pixel.dtype), pixel)

            with autocast("cuda"):
                if use_caps:
                    x_img, x_cap = model(pixel, cap_ids, cap_mask)
                elif mix_at_clip:
                    # Stop before the projection head; the mix happens below and
                    # to_hyperbolic finishes the job on the primary GPU.
                    clip_emb = model(pixel, return_clip_emb=True)
                    x_cap = None
                else:
                    x_img = model(pixel)
                    x_cap = None
                t_anc = anchor_tangent_now()
                if t_anc is None:
                    x_anc, _ = core.encode_text(anchor_ids, anchor_mask)
                x_fam = (core.encode_text(fam_ids, fam_mask)[0]
                         if fam_ids is not None else None)
            if t_anc is not None:
                # fp32, outside autocast: the hyperbolic ops are unstable in fp16
                # (same reason AttributionCLIP.to_hyperbolic disables autocast).
                with autocast("cuda", enabled=False):
                    x_anc = exp_map0(t_anc.float(), curv=args.curv)
            if args.mixup_alpha > 0:
                # EntailmentConeLoss is untouched — the mixed target is expressed by
                # calling it twice, exactly as the multi-view trainer folds views into
                # the batch. Only the mixing POINT differs between the two modes.
                with autocast("cuda", enabled=False):
                    lam = mixup_beta.sample().item()
                    if mix_at_clip:
                        e = clip_emb.float()
                        perm = torch.randperm(e.size(0), device=device)
                        # Re-normalise: _clip_image only ever emits unit vectors, and
                        # a convex combination of two of them is SHORTER. Without this
                        # every mixed sample would get a smaller tangent and land closer
                        # to the origin, turning mixup into a norm regulariser as well.
                        mixed = F.normalize(lam * e + (1 - lam) * e[perm], dim=-1)
                        x_mix, _ = core.to_hyperbolic(mixed, core.image_radius)
                    else:
                        # Tangent space at the origin: exp_map0 is radial, so a convex
                        # combination there is the manifold-mixup analogue (mixing on
                        # the hyperboloid itself would need a geodesic).
                        perm = torch.randperm(x_img.size(0), device=device)
                        t = log_map0(x_img.float(), curv=args.curv)
                        mixed_t = lam * t + (1 - lam) * t[perm]
                        if core.image_radius > 0:
                            mixed_t = F.normalize(mixed_t, dim=-1) * core.image_radius
                        x_mix = exp_map0(mixed_t, curv=args.curv)
                sp = sin_psi_now()
                loss_a, stats = (cone_loss(x_mix, x_anc, labels, sp) if axis
                                 else cone_loss(x_mix, x_anc, labels))
                loss_b, _     = (cone_loss(x_mix, x_anc, labels[perm], sp) if axis
                                 else cone_loss(x_mix, x_anc, labels[perm]))
                loss = lam * loss_a + (1 - lam) * loss_b
            else:
                loss, stats = (cone_loss(x_img, x_anc, labels, sin_psi_now()) if axis
                               else cone_loss(x_img, x_anc, labels,
                                              x_cap=x_cap, x_fam=x_fam))

            optimizer.zero_grad()
            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            if backbone:
                nn.utils.clip_grad_norm_(backbone, 1.0)
            if geometric:
                nn.utils.clip_grad_norm_(geometric, 1.0)
            scaler.step(optimizer)
            scaler.update()
            scheduler.step()
            if axis and anchor_tangent is not None:
                # q reads a normalised direction, so the radial component of the gradient
                # on the anchor is exactly zero. Set the norm to the depth the aperture
                # implies, ‖a‖ = 2K/sin ψ, so the stored anchor is still the point it
                # represents — for the snapshots, the checkpoint and the eval.
                with torch.no_grad():
                    rc = args.curv ** 0.5
                    want = torch.asinh(
                        rc * depth_from_sin_psi(sin_psi_now(), args.min_radius)) / rc
                    n = anchor_tangent.norm(dim=-1, keepdim=True).clamp_min(1e-8)
                    anchor_tangent.mul_(want.unsqueeze(1) / n)
            elif args.anchor_norm_range and anchor_tangent is not None:
                # Projection onto the norm range, not a penalty: psi is a function of
                # ‖t‖ alone, so this pins the aperture band exactly. Below the lower
                # bound every cone degenerates into a halfspace and argmin xi is a
                # cosine again.
                lo, hi = args.anchor_norm_range
                with torch.no_grad():
                    n = anchor_tangent.norm(dim=-1, keepdim=True)
                    anchor_tangent.mul_(n.clamp(lo, hi) / n.clamp_min(1e-8))

            sums["loss"] += loss.item()
            for k in base_keys + ce_keys + axreg_keys + sep_keys + fam_keys:
                sums[k] += stats[k].item()
            if use_caps:
                for k in cap_keys:
                    sums[k] += stats[k].item()

            # ── Step-level trace ─────────────────────────────────────────────
            # INSTANTANEOUS values, not the running mean the tqdm bar shows: the
            # quantity of interest here is a transient. In the last axis run the
            # anchors went from min∠ 78.7° to 41.2° inside epoch 1, so an epoch
            # average of that trajectory is a number no reading can recover.
            if stat_csv is not None and (global_step % args.log_every == 0
                                         or global_step == 1):
                row = {"step": global_step, "epoch": epoch,
                       "lr": scheduler.get_last_lr()[0], "loss": loss.item(),
                       **{k: stats[k].item() for k in stat_csv_keys}}
                if stat_csv.tell() == 0:
                    stat_csv.write(",".join(row) + "\n")
                stat_csv.write(",".join(f"{v:.6g}" for v in row.values()) + "\n")
                stat_csv.flush()      # a killed job keeps everything up to the kill

            if (snap_every and plot_epoch_snapshot is not None
                    and global_step % snap_every == 0):
                # The current TRAINING batch, so a frame costs no extra forward pass.
                # diag_state carries the basis fit before step 1, so every frame —
                # intra-epoch and per-epoch alike — lands in the SAME 2-D frame.
                # --mixup_at clip never materialises the unmixed x_img (the mix happens
                # before the projection head), so the mixed points are all there is.
                x_snap = x_mix if mix_at_clip else x_img
                with torch.no_grad():
                    diag_state = plot_epoch_snapshot(
                        x_snap.detach().float().cpu().numpy(), labels.tolist(),
                        x_anc.detach(), class_names,
                        Path(args.diag_plot_dir) / f"step_{global_step:07d}.png",
                        curv=args.curv, min_radius=args.min_radius,
                        psi=snap_psi(), state=diag_state, seed=args.seed,
                        title=f"epoch {epoch} · step {global_step}")

            if step % 25 == 0 or step == steps_per_epoch:
                if axis:
                    post = {
                        "loss": f"{sums['loss']/step:.3f}",
                        "q":    f"{sums['q_pos']/step:.3f}",
                        "acc":  f"{sums['cone_acc']/step:.3f}",
                        "ψ":    f"{sums['psi_deg']/step:.1f}°",
                    }
                else:
                    post = {
                        "loss": f"{sums['loss']/step:.3f}",
                        "ic":   f"{sums['loss_img_in_cls']/step:.3f}",
                        "acc":  f"{sums['cone_acc']/step:.3f}",
                        "ψa":   f"{sums['mean_psi_anc']/step:.3f}",
                    }
                if use_caps:
                    post["cc"] = f"{sums['loss_cap_in_cls']/step:.3f}"
                    post["ip"] = f"{sums['loss_img_in_cap']/step:.3f}"
                    post["ψc"] = f"{sums['mean_psi_cap']/step:.3f}"
                bar.set_postfix(**post)

        avg = {k: v / steps_per_epoch for k, v in sums.items()}
        if args.loss == "axis":
            print(f"\nEpoch {epoch}: train loss={avg['loss']:.4f}  "
                  f"pos={avg['loss_pos']:.4f}  ap={avg['loss_ap']:+.4f}  "
                  f"neg={avg['loss_neg']:.4f}  sep={avg['loss_sep']:.4f}  "
                  f"lr={scheduler.get_last_lr()[0]:.2e}")
            # psi SPREAD is the line to read: if it stays a point, every class has the
            # same aperture and argmin q IS argmax cos, however high the accuracy goes.
            # inside vs nu is the coverage the cone actually reached; viol_mass is the
            # quantity the aperture term drives to nu, so the two together say whether it
            # got there or is still in transit.
            print(f"           acc={100*avg['cone_acc']:.1f}%  "
                  f"inside={100*avg['inside_img']:.1f}% (out {100*(1-avg['inside_img']):.1f}%"
                  f" vs ν {100*args.nu:.0f}%)  "
                  f"viol={avg['viol_mass']:.3f}  "
                  f"q_pos={avg['q_pos']:.3f}  "
                  f"ψ∈[{avg['psi_min_deg']:.1f},{avg['psi_max_deg']:.1f}]°"
                  f" (μ{avg['psi_deg']:.1f}°)  "
                  f"min∠={avg['sep_min_deg']:.1f}°  mean∠={avg['sep_mean_deg']:.1f}°  "
                  f"overlap={100*avg['sep_overlap']:.1f}%  "
                  f"‖a_anc‖={avg['anc_norm']:.2f}"
                  + (f"  ‖t_anc‖={anchor_tangent.norm(dim=-1).mean().item():.2f}"
                     if anchor_tangent is not None else ""))
        else:
            line1 = (f"\nEpoch {epoch}: train loss={avg['loss']:.4f}  "
                     f"L_img_cls={avg['loss_img_in_cls']:.4f}"
                     f"  (pos={avg['loss_pos']:.4f} neg={avg['loss_neg']:.4f})")
            if use_caps:
                line1 += (f"  L_cap_cls={avg['loss_cap_in_cls']:.4f}"
                          f"  L_img_cap={avg['loss_img_in_cap']:.4f}")
            line1 += f"  L_norm={avg['loss_norm']:.4f}"
            if axreg_keys:
                # frac_shallow is the one to watch: an image shallower than its own
                # anchor is outside every cone by construction and its xi is pinned at
                # the acos clamp, where the hinge has no gradient. It should be ~0.
                line1 += (f"  L_axis={avg['loss_axis']:.4f}"
                          f"  shallow={100 * avg['frac_shallow']:.1f}%")
            if ce_keys:
                line1 += f"  L_ce={avg['loss_ce']:.4f}  τ={avg['ce_tau']:.3f}"
            # Unconditional, not gated on lambda_sep: this is the anchor-collapse
            # readout (78.7° at random init → 41.2° within epoch 1 last run) and the
            # Poincare snapshots cannot show it — 22 near-orthogonal directions in
            # 128-d land on one blob in any 2-D basis, including at init.
            # 2ψ/min∠ is stop criterion 1a (must fall below 1; sweepwin sits at 12.8,
            # Phase B's `flat` reached 1.2).
            line1 += (f"  min∠={avg['sep_min_deg']:.1f}°"
                      f"  mean∠={avg['sep_mean_deg']:.1f}°"
                      f"  overlap={100*avg['sep_overlap']:.0f}%"
                      f"  2ψ/min∠={2*math.degrees(avg['mean_psi_anc'])/max(avg['sep_min_deg'], 1e-6):.1f}")
            if sep_keys:
                line1 += (f"  L_sep={avg['loss_sep']:.4f}"
                          f"  max∠={avg['sep_max_deg']:.1f}°")
            if fam_keys:
                line1 += (f"  L_famA={avg['loss_fam_anc']:.4f}"
                          f"  L_famI={avg['loss_fam_img']:.4f}"
                          f"  in_fam={100*avg['inside_family']:.0f}%"
                          f"  fam_acc={100*avg['family_acc']:.1f}%"
                          f"  ψf={avg['mean_psi_fam']:.3f}")
            if anchor_drift is not None:
                line1 += f"  drift_s={F.softplus(anchor_drift).item():.4f}"
            line1 += f"  lr={scheduler.get_last_lr()[0]:.2e}"
            print(line1)
            print(f"           cone_acc={100*avg['cone_acc']:.1f}%  "
                  f"inside_img={100*avg['inside_img']:.1f}%  "
                  f"ψ_anc={avg['mean_psi_anc']:.3f}"
                  f"∈[{avg['psi_min_deg']:.1f},{avg['psi_max_deg']:.1f}]°  "
                  f"ξ_img→anc={avg['mean_xi_img_anc']:.3f}  "
                  f"ξ_sat={100*avg['xi_sat']:.0f}%  "
                  f"‖x_anc‖={avg['mean_anc_norm']:.2f}"
                  + (f"  ‖t_anc‖={anchor_tangent.norm(dim=-1).mean().item():.2f}"
                     if anchor_tangent is not None else ""))
            if use_caps:
                print(f"           inside_cap={100*avg['inside_cap']:.1f}%  "
                      f"inside_img_in_cap={100*avg['inside_img_cap']:.1f}%  "
                      f"ψ_cap={avg['mean_psi_cap']:.3f}  "
                      f"ξ_cap→anc={avg['mean_xi_cap_anc']:.3f}  "
                      f"ξ_img→cap={avg['mean_xi_img_cap']:.3f}  "
                      f"‖t̄_cap‖={avg['mean_cap_norm']:.2f}")
        # ── Validation ───────────────────────────────────────────────────────
        # Anchors under the CURRENT weights: text ones must be re-encoded, the free
        # ones come out of anchor_tangent_now(). eval() first — the text anchors must
        # not be encoded with LoRA dropout active.
        core.eval()
        with torch.no_grad():
            t_anc_val = anchor_tangent_now()
            if t_anc_val is None:
                x_anc_val, _ = core.encode_text(anchor_ids, anchor_mask)
            else:
                x_anc_val = exp_map0(t_anc_val.float(), curv=args.curv)
        val = run_validation(core, val_loader, x_anc_val, class_names, device, args.curv,
                             collect=4000 if plot_epoch_snapshot else 0,
                             predict=val_predict)
        print(f"  val: overall={100*val['overall_acc']:.1f}%  "
              f"balanced={100*val['balanced_acc']:.1f}%  ({val['total']} samples)")
        for c, a in val["per_class_acc"].items():
            print(f"    {c:10s}: {100*a:5.1f}%")

        if plot_epoch_snapshot is not None:
            # diag_state carries the HoroPCA fit and the Frechet-mean isometry from
            # the first epoch, so every frame is in the SAME 2-D frame — otherwise the
            # basis rotates each epoch and "how the anchors moved" is unreadable.
            diag_state = plot_epoch_snapshot(
                val["emb"], val["emb_labels"], x_anc_val, class_names,
                Path(args.diag_plot_dir) / f"epoch_{epoch:02d}.png",
                curv=args.curv, min_radius=args.min_radius,
                psi=snap_psi(), state=diag_state, seed=args.seed,
                title=f"epoch {epoch}")

        # ── Save best checkpoint by balanced val accuracy ────────────────────
        if val["balanced_acc"] > best_balanced:
            best_balanced = val["balanced_acc"]
            torch.save(
                {
                    "lora_state":      core.clip.state_dict(),
                    "projection":      core.projection.state_dict(),
                    "clip_name":       args.clip_name,
                    "lora_r":          args.lora_r,
                    "lora_alpha":      args.lora_alpha,
                    # Which modules got adapters: the key set of lora_state depends
                    # on it, and every loader does a STRICT load_state_dict.
                    "lora_target":     args.lora_target,
                    "hyperbolic_dim":  args.hyperbolic_dim,
                    "init_scale":      args.init_scale,
                    "init_depth":      args.init_depth,
                    "image_radius":    args.fixed_image_radius,
                    "radial_margin":   args.radial_margin,
                    "anchors_only":    args.anchors_only,
                    "curv":            args.curv,
                    "min_radius":      args.min_radius,
                    "class_names":     class_names,
                    "anchor_texts":    anchor_texts,
                    "anchor_init":     args.anchor_init,
                    "anchor_prompts":  args.anchor_prompts,
                    "anchor_norm_range": args.anchor_norm_range,
                    # Free-anchor modes only (image_centroid / text_free): the learned
                    # anchors in tangent space, in class_names order. Inference lifts
                    # them with exp_map0. None in 'text' mode, where the eval re-encodes
                    # anchor_texts instead.
                    "anchor_tangent":  (t_anc_val.detach().cpu()
                                        if t_anc_val is not None else None),
                    "anchor_drift":    (F.softplus(anchor_drift).item()
                                        if anchor_drift is not None else None),
                    "lambda_ce":       args.lambda_ce,
                    "ce_tau":          (F.softplus(cone_loss.ce_tau_raw).item()
                                        if args.lambda_ce > 0 else None),
                    "lambda_hinge":    args.lambda_hinge,
                    # Which decision rule the eval must use: argmin xi for 'cone',
                    # argmin q for 'axis'. Reading it wrong gives a plausible number,
                    # not an error.
                    "loss":            args.loss,
                    "lambda_aperture": args.lambda_aperture,
                    "nu":              args.nu,
                    "lr_min":          args.lr_min,
                    # The aperture is a free parameter now, not a function of the anchor
                    # norm. The eval must read THIS, not re-derive it from the depth.
                    "anchor_sin_psi":  (sin_psi_now().detach().cpu()
                                        if anchor_psi_raw is not None else None),
                    "psi_range":       args.psi_range,
                    "pos_mode":        args.pos_mode,
                    "neg_samples":     args.neg_samples,
                    "optimizer":       args.optimizer,
                    "momentum":        args.momentum,
                    "lr":              args.lr,
                    "norm_mode":       args.norm_mode,
                    "target_norm":     args.target_norm,
                    "lambda_norm":     args.lambda_norm,
                    "lambda_sep":      args.lambda_sep,
                    "separation_margin": args.separation_margin,
                    "inside_margin":  args.inside_margin,
                    "theta_max":       args.theta_max,
                    # Everything the evaluator needs to rebuild the family readout
                    # without re-reading the tree from disk: the names in anchor order,
                    # the class->family index, and the depth the families were pinned
                    # to (psi is a function of that norm alone).
                    "hierarchy":         args.hierarchy,
                    "family_names":      family_names,
                    "family_of":         (family_of.cpu().tolist()
                                          if family_of is not None else None),
                    "target_norm_family": args.target_norm_family,
                    "lambda_family":     args.lambda_family,
                    "fam_tau":           (F.softplus(cone_loss.fam_tau_raw).item()
                                          if args.lambda_family > 0 else None),
                    "train_augment":   args.train_augment,
                    "aug_policy":      args.aug_policy,
                    "mixup_alpha":     args.mixup_alpha,
                    "mixup_at":        args.mixup_at,
                    "blackout_max":    args.blackout_max,
                    "generators":      args.generators,
                    "semantics":       args.semantics,
                    "val_balanced":    val["balanced_acc"],
                    "epoch":           epoch,
                },
                out_path,
            )
            print(f"  ↳ saved checkpoint (balanced val={100*best_balanced:.1f}%) → {out_path}")

    if stat_csv is not None:
        stat_csv.close()
        print(f"Step-level trace: {Path(args.diag_plot_dir) / 'stats.csv'}")

    print(f"\nBest balanced val accuracy: {100*best_balanced:.1f}%  ({out_path})")


if __name__ == "__main__":
    main()
