"""Does the model keep the FAMILY when it loses the leaf — and does it know?

This is the one claim a cosine cannot express. Under JPEG65 the 22-way accuracy of
every cone model collapses to ~0.19 while its AUC stays at 0.64, i.e. the prediction
is wrong and the model is confident anyway. A nested-cone model has somewhere else to
go: answer the family, and say so.

Three readouts on the same embeddings, per degradation level:

  leaf      argmin_c xi_c over the 22 model anchors          (what the model reports today)
  family    argmin_f xi_f over the F family anchors          (a level a flat softmax has not got)
  induced   family_of[argmin_c xi_c]                         (the family the leaf answer implies)

`family` above `induced` means the family anchors carry information the leaf ranking has
already lost — which is the whole point of putting them there.

And the abstention, which needs no threshold to be tuned:

  abstain   min_c (xi_c - psi_c) > 0   ==  outside EVERY leaf cone == "none of these"

Read `leaf | kept` against `leaf`: if abstaining removes mostly-wrong predictions the
rule is calibrated, and `family | abstained` says whether the coarse answer is still
right where the fine one was refused.

    IAB_EXCLUDE_GENERATORS=dalle3 python -m tests.probe_family_readout \\
        $CK/attribution_22cls_phaseb_hifi_vitl14.pt --levels 0 3 5

Levels are the eval's: 0=clean 1=DS0.5 2=DS0.25 3=JPEG65 4=JPEG30 5=Blur3 6=Blur5.
Balanced (macro-recall) accuracy throughout — the test split is 95.5% synthetic. GPU node.
"""
import argparse
import os

os.environ.setdefault("IAB_EXCLUDE_GENERATORS", "dalle3")

import torch
from torch.utils.data import DataLoader
from tqdm import tqdm

from comparison.training.test_hypclip import harness_class_names
from data.degradations import LEVEL_LABELS
from geometry.lorentz import half_aperture
from losses.attribution_loss import _pairwise_xi
from tests.probe_anchor_spread import load_any
from tests.probe_degradation_shift import paired_datasets


def family_texts(names):
    """Regenerated from the checkpoint's family NAMES, byte-identical to training.

    train_attribution.build_family_anchors is deterministic in the names, so the
    checkpoint does not need to carry the sentences.
    """
    return ["A real image" if n == "real"
            else f"A synthetic image generated by a model of the {n} family"
            for n in names]


def load_family(path, model, clip_name, names, device):
    """(family anchors (F,D), psi_fam (F,), family_of in HARNESS order, names, curv)."""
    from transformers import CLIPTokenizer
    ckpt = torch.load(path, map_location="cpu", weights_only=False)
    if ckpt.get("hierarchy", "none") == "none":
        raise ValueError(f"{os.path.basename(path)} was trained without --hierarchy")

    # family_of is stored in the TRAINING class order; the evaluator works in the
    # harness order. Permuting it is not optional — get it wrong and every family is
    # silently mislabelled while every number still looks plausible.
    train_names = ckpt["class_names"]
    if set(train_names) != set(names):
        raise ValueError(
            f"checkpoint was trained on a different label space: "
            f"missing={sorted(set(names) - set(train_names))}, "
            f"extra={sorted(set(train_names) - set(names))} — "
            f"check IAB_EXCLUDE_GENERATORS")
    fam_of = torch.tensor([ckpt["family_of"][train_names.index(n)] for n in names],
                          dtype=torch.long, device=device)

    fam_names = ckpt["family_names"]
    tok = CLIPTokenizer.from_pretrained(clip_name)
    t = tok(family_texts(fam_names), return_tensors="pt", padding="max_length",
            truncation=True, max_length=77)
    with torch.no_grad():
        x_fam, _ = model.encode_text(t["input_ids"].to(device),
                                     t["attention_mask"].to(device))
    curv = float(ckpt.get("curv", 1.0))
    psi_fam = half_aperture(x_fam, curv=curv, min_radius=ckpt.get("min_radius", 0.1))
    return x_fam.detach(), psi_fam.detach(), fam_of, fam_names, curv


def macro_recall(pred, true, k):
    """Mean per-class recall, over the classes actually present."""
    got = [(pred[true == c] == c).float().mean().item()
           for c in range(k) if (true == c).any()]
    return sum(got) / len(got) if got else float("nan")


@torch.no_grad()
def embed(model, ds, args, device, desc):
    loader = DataLoader(ds, batch_size=args.batch_size, shuffle=False,
                        num_workers=args.num_workers)
    xs, ys = [], []
    names = harness_class_names()
    idx = {n: i for i, n in enumerate(names)}
    for batch in tqdm(loader, desc=desc, leave=False):
        x = model.encode_image(batch["pixel_values"].to(device))
        xs.append((x[0] if isinstance(x, tuple) else x).cpu())
        ys.append(torch.tensor([idx[g] for g in batch["generator"]]))
    return torch.cat(xs), torch.cat(ys)


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("checkpoint")
    p.add_argument("--levels", type=int, nargs="+", default=[0, 3, 5])
    p.add_argument("--dataset_path", default=os.environ.get("FAST", "") + "/datasets/iab_dataset")
    p.add_argument("--captions_dir", default=os.environ.get("WORK", "") + "/hyp_fine_tuning/iab_captions")
    p.add_argument("--manifest", default=os.environ.get("WORK", "") + "/hyp_fine_tuning/split_manifest_22cls.json")
    p.add_argument("--n", type=int, default=8000)
    p.add_argument("--batch_size", type=int, default=64)
    p.add_argument("--num_workers", type=int, default=8)
    args = p.parse_args()

    device = "cuda" if torch.cuda.is_available() else "cpu"
    names = harness_class_names()
    model, x_anc, psi_anc, desc, clip_name = load_any(args.checkpoint, device)
    x_anc, psi_anc = x_anc.detach(), psi_anc.detach()
    x_fam, psi_fam, fam_of, fam_names, curv = load_family(
        args.checkpoint, model, clip_name, names, device)
    K, Fm = x_anc.shape[0], x_fam.shape[0]
    print(f"\n{os.path.basename(args.checkpoint)}   ({desc})")
    print(f"  {K} leaves, {Fm} families: " + ", ".join(fam_names))
    print(f"  ψ leaf mean {psi_anc.mean():.4f}   ψ family mean {psi_fam.mean():.4f}")

    rows = []
    for level in args.levels:
        clean_ds, deg_ds = paired_datasets(args, names, clip_name, level)
        ds = clean_ds if level == 0 else deg_ds
        x, y = embed(model, ds, args, device, LEVEL_LABELS.get(level, str(level)))
        x = x.to(device)
        y = y.to(device)

        xi_leaf = _pairwise_xi(x_anc, x, curv).T              # (N, K)
        xi_fam = _pairwise_xi(x_fam, x, curv).T               # (N, F)
        y_fam = fam_of[y]

        leaf_pred = xi_leaf.argmin(1)
        fam_pred = xi_fam.argmin(1)
        induced = fam_of[leaf_pred]
        abstain = (xi_leaf - psi_anc.unsqueeze(0)).min(1).values > 0

        leaf = macro_recall(leaf_pred, y, K)
        fam = macro_recall(fam_pred, y_fam, Fm)
        ind = macro_recall(induced, y_fam, Fm)
        rate = abstain.float().mean().item()
        kept = macro_recall(leaf_pred[~abstain], y[~abstain], K) if (~abstain).any() else float("nan")
        drop = macro_recall(fam_pred[abstain], y_fam[abstain], Fm) if abstain.any() else float("nan")
        rows.append((LEVEL_LABELS.get(level, str(level)), leaf, ind, fam, rate, kept, drop))

    print(f"\n{'level':8s} {'leaf':>8s} {'induced':>9s} {'family':>8s} "
          f"{'abstain':>9s} {'leaf|kept':>10s} {'fam|absta':>10s}")
    for r in rows:
        print(f"{r[0]:8s} {r[1]:8.3f} {r[2]:9.3f} {r[3]:8.3f} "
              f"{r[4]:9.1%} {r[5]:10.3f} {r[6]:10.3f}")
    print("\n'family' above 'induced' means the family anchors hold information the leaf\n"
          "ranking has already lost. 'leaf|kept' above 'leaf' means the abstention removes\n"
          "wrong predictions rather than random ones — the part a flat softmax cannot do.")


if __name__ == "__main__":
    main()
