"""Self-check for the free/text anchors + train-time augmentation.

Runs on CPU, no dataset needed:  python -m tests.test_centroid_anchors

Covers the things that fail silently:
  1. the anchor REORDERING from the checkpoint's class order ('real' first) to
     the harness label order ('real' last) — a wrong permutation still produces
     a full set of metrics, just meaningless ones;
  2. the eval re-encoding the CHECKPOINT's prompts rather than the default
     templates — with --anchor_prompts, using the templates would evaluate a
     model against anchors it was never trained on, and nothing would raise;
  3. the structural prompt file covering every class, with no two classes
     sharing a sentence;
  4. random_degradation actually firing (and never changing the image size,
     which would break the batch collation).
"""
import json
import os
from pathlib import Path

os.environ.setdefault("IAB_EXCLUDE_GENERATORS", "dalle3")   # 22-class map

import torch
from PIL import Image, ImageDraw

from comparison.training.test_hypclip import harness_class_names, load_anchors
from data.degradations import random_degradation
from train_attribution import build_anchors

PROMPTS = Path(__file__).resolve().parent.parent / "data" / "anchor_prompts_structural.json"


def test_anchor_reordering():
    harness = harness_class_names()
    assert harness[-1] == "real", f"expected 'real' last in harness order, got {harness[-1]}"
    K = len(harness)
    assert K == 22, f"IAB_EXCLUDE_GENERATORS=dalle3 should give 22 classes, got {K}"

    # Checkpoint order = train_attribution.build_anchors(): 'real' first.
    ckpt_names = ["real"] + [n for n in harness if n != "real"]
    # Row i is the i-th scaled basis vector → the class it belongs to is recoverable
    # from argmax, so a wrong permutation cannot pass.
    tangent = torch.eye(K) * 2.0
    ckpt = {"class_names": ckpt_names, "anchor_tangent": tangent}

    x_anc = load_anchors(ckpt, model=None, curv=1.0, device="cpu")
    assert x_anc.shape == (K, K), x_anc.shape
    for i, name in enumerate(harness):
        expected_row = ckpt_names.index(name)
        got = int(x_anc[i].argmax())
        assert got == expected_row, f"class {name}: anchor row {got}, expected {expected_row}"
    # exp_map0 only rescales along the direction — norms must stay equal and > 0
    norms = x_anc.norm(dim=-1)
    assert torch.allclose(norms, norms[0]) and norms[0] > 0, norms

    missing = {"class_names": ckpt_names[:-1], "anchor_tangent": tangent[:-1]}
    try:
        load_anchors(missing, model=None, curv=1.0, device="cpu")
    except ValueError:
        pass
    else:
        raise AssertionError("a checkpoint missing a class must not load silently")


class _FakeTextEncoder:
    """Stands in for AttributionCLIP: returns the token-id sums, so the anchor row
    for a class is a fingerprint of the SENTENCE the eval chose to encode."""
    def encode_text(self, input_ids, attention_mask):
        return input_ids.float().sum(dim=1, keepdim=True), None


def test_text_anchors_come_from_the_checkpoint():
    import comparison.training.test_hypclip as th

    harness = harness_class_names()
    ckpt_names = ["real"] + [n for n in harness if n != "real"]
    ckpt_texts = [f"sentence for {n}" for n in ckpt_names]
    ckpt = {"class_names": ckpt_names, "anchor_texts": ckpt_texts,
            "clip_name": "openai/clip-vit-large-patch14"}

    seen = {}

    class _Tok:
        @staticmethod
        def from_pretrained(_):
            def tok(texts, **kw):
                seen["texts"] = list(texts)
                ids = torch.arange(len(texts)).unsqueeze(1).repeat(1, 3)
                return {"input_ids": ids, "attention_mask": torch.ones_like(ids)}
            return tok

    orig = th.CLIPTokenizer
    th.CLIPTokenizer = _Tok
    try:
        load_anchors(ckpt, model=_FakeTextEncoder(), curv=1.0, device="cpu")
    finally:
        th.CLIPTokenizer = orig

    # The checkpoint's own sentences, permuted into harness order — NOT the templates.
    assert seen["texts"] == [f"sentence for {n}" for n in harness], seen["texts"]
    assert "A synthetic image generated by" not in " ".join(seen["texts"]), \
        "load_anchors fell back to the default templates despite ckpt['anchor_texts']"


def test_structural_prompts():
    prompts = {k: v for k, v in json.loads(PROMPTS.read_text()).items()
               if not k.startswith("_")}
    harness = harness_class_names()
    missing = [c for c in harness if c not in prompts]
    assert not missing, f"prompt file is missing {missing}"
    assert len(set(prompts.values())) == len(prompts), "two classes share a sentence"

    names, texts = build_anchors(harness, str(PROMPTS))
    assert names[0] == "real", names[:2]
    assert texts[0] == prompts["real"], texts[0]
    assert all(t == prompts[n] for n, t in zip(names, texts))
    # The whole point: the sentences must not be one template with a swapped name.
    words = [set(t.lower().split()) for t in texts]
    shared = set.intersection(*words)
    assert len(shared) <= 1, f"all 22 prompts share the words {shared} — too templatey"

    try:
        build_anchors(harness + ["nonexistent_gen"], str(PROMPTS))
    except ValueError:
        pass
    else:
        raise AssertionError("a class with no prompt must not pass silently")


def test_random_degradation():
    img = Image.new("RGB", (256, 200))
    ImageDraw.Draw(img).rectangle([20, 20, 180, 150], fill=(200, 30, 60))
    outs = [random_degradation(img) for _ in range(50)]
    assert all(o.size == img.size and o.mode == "RGB" for o in outs)
    changed = sum(o.tobytes() != img.tobytes() for o in outs)
    assert 25 < changed < 50, f"{changed}/50 augmented — check the per-family probabilities"


if __name__ == "__main__":
    test_anchor_reordering()
    test_text_anchors_come_from_the_checkpoint()
    test_structural_prompts()
    test_random_degradation()
    print("ok")
