"""
Self-contained checks for the family-cone additions.

Two groups:
  * taxonomy  — pure Python (data/families.py), always runs.
  * loss      — requires torch; verifies backward-compat and the new family
                terms. Skipped with a clear message if torch is unavailable
                (e.g. on a dev box without the training env).

Run:  python -m tests.test_family_loss
"""
from data.families import family_of, family_anchor_text, build_family_structures


def test_taxonomy() -> None:
    # lineage grouping
    for g in ("SD1_5", "SD2_1", "SD3", "SD3_5", "SDXL"):
        assert family_of(g) == "Stable Diffusion", g
    assert family_of("mid-5.2") == "Midjourney"
    assert family_of("mid-6.0") == "Midjourney"
    assert family_of("4o") == "OpenAI"
    assert family_of("dalle3") == "OpenAI"
    # singletons map to themselves
    for g in ("FLUX", "gemini", "grok3", "real", "PIXART"):
        assert family_of(g) == g, g
    # anchor texts
    assert family_anchor_text("real") == "A real image"
    assert family_anchor_text("Stable Diffusion") == \
        "A synthetic image generated by a Stable Diffusion model"
    # singleton family anchor == its generator class anchor
    assert family_anchor_text("FLUX") == "A synthetic image generated by FLUX"

    class_names = ["real", "SD1_5", "SD2_1", "SD3", "SDXL", "FLUX",
                   "mid-5.2", "mid-6.0", "4o"]
    fam_names, fam_texts, g2f = build_family_structures(class_names)
    # index consistency
    for c, fi in zip(class_names, g2f):
        assert fam_names[fi] == family_of(c), (c, fam_names[fi])
    # SD members collapse to a single family index
    sd_idx = {g2f[i] for i, c in enumerate(class_names) if c.startswith("SD")}
    assert len(sd_idx) == 1, sd_idx
    assert fam_texts == [family_anchor_text(f) for f in fam_names]
    # SD family survives even when one member (SD3_5) is held out of training
    assert "Stable Diffusion" in fam_names
    print(f"  taxonomy OK — {len(fam_names)} families for {len(class_names)} generators: {fam_names}")


def test_loss() -> None:
    try:
        import torch
    except ImportError:
        print("  loss SKIPPED — torch not installed (run on the training env)")
        return

    from losses.attribution_loss import EntailmentConeLoss

    torch.manual_seed(0)
    B, K, D, Fn = 16, 6, 8, 3
    curv, min_radius = 1.0, 0.5
    x_img = torch.randn(B, D)
    x_anc = torch.randn(K, D) * 3.0
    x_fam = torch.randn(Fn, D) * 2.0
    labels = torch.randint(0, K, (B,))
    gen_family = torch.randint(0, Fn, (K,))
    labels_family = gen_family[labels]
    common = dict(curv=curv, min_radius=min_radius, margin=0.3, lambda_neg=1.0,
                  lambda_norm=0.5, target_norm=4.0)

    # 1) Backward-compat: family lambdas at 0 ⇒ passing family tensors changes
    #    nothing vs not passing them at all.
    loss_mod = EntailmentConeLoss(**common)
    l_without, _ = loss_mod(x_img, x_anc, labels)
    l_with, st = loss_mod(x_img, x_anc, labels, x_fam=x_fam,
                          gen_family=gen_family, labels_family=labels_family)
    assert torch.allclose(l_without, l_with), (l_without.item(), l_with.item())
    assert "loss_img_in_family" not in st  # family stats absent when disabled
    print(f"  backward-compat OK — loss unchanged at λ_family=0 ({l_with.item():.4f})")

    # 2) Family terms active: finite loss + new stats present.
    loss_fam = EntailmentConeLoss(
        **common, lambda_img_in_family=1.0, lambda_gen_in_family=1.0,
        target_norm_family=2.5)
    l, st = loss_fam(x_img, x_anc, labels, x_fam=x_fam,
                     gen_family=gen_family, labels_family=labels_family)
    assert torch.isfinite(l), l
    for k in ("loss_img_in_family", "loss_gen_in_family", "loss_norm_family",
              "family_cone_acc", "mean_psi_fam"):
        assert k in st, k
    print(f"  family terms OK — loss={l.item():.4f}  "
          f"L_gen_fam={st['loss_gen_in_family'].item():.4f}  "
          f"L_img_fam={st['loss_img_in_family'].item():.4f}")

    # 3) Structural sanity: nesting generator anchors right at their family
    #    anchor drives L_gen_in_family below the random-init value.
    x_anc_nested = x_fam[gen_family] + 0.01 * torch.randn(K, D)
    _, st_far = loss_fam(x_img, x_anc, labels, x_fam=x_fam,
                         gen_family=gen_family, labels_family=labels_family)
    _, st_near = loss_fam(x_img, x_anc_nested, labels, x_fam=x_fam,
                          gen_family=gen_family, labels_family=labels_family)
    assert st_near["loss_gen_in_family"] <= st_far["loss_gen_in_family"] + 1e-6, \
        (st_near["loss_gen_in_family"].item(), st_far["loss_gen_in_family"].item())
    print(f"  nesting sanity OK — L_gen_in_family far={st_far['loss_gen_in_family'].item():.4f} "
          f"≥ near={st_near['loss_gen_in_family'].item():.4f}")


if __name__ == "__main__":
    print("test_taxonomy:")
    test_taxonomy()
    print("test_loss:")
    test_loss()
    print("ALL CHECKS PASSED")
