import torch
import torch.nn.functional as F


def clip_contrastive_loss(
    image_embeds: torch.Tensor,
    text_embeds: torch.Tensor,
    logit_scale: torch.Tensor,
) -> torch.Tensor:
    """
    Symmetric InfoNCE (CLIP) loss.

    Args:
        image_embeds:  (B, D) L2-normalised image embeddings.
        text_embeds:   (B, D) L2-normalised text embeddings.
        logit_scale:   Scalar tensor (exp of learned log-temperature).
                       Positive; high value = sharp distribution.

    Returns:
        Scalar loss averaged over both directions (image→text and text→image).

    Each image must match its paired text and not the others in the batch.
    In-batch negatives include both real and fake captions, so the model
    is pushed to distinguish "Real image of …" from "Synthetic image
    generated by FLUX …" in the same batch.
    """
    logits = logit_scale * (image_embeds @ text_embeds.T)   # (B, B)
    labels = torch.arange(len(logits), device=logits.device)
    loss_i2t = F.cross_entropy(logits,   labels)
    loss_t2i = F.cross_entropy(logits.T, labels)
    return (loss_i2t + loss_t2i) / 2
