"""
Euclidean prototype classification loss — the standard cosine-similarity
counterpart to the hyperbolic entailment-cone loss (losses.attribution_loss).

Each image is classified against the fixed text anchors ("A real image",
"A synthetic image generated by FLUX", ...) by cosine similarity, scaled by a
learnable temperature, and trained with cross-entropy:

    logits[i, c] = logit_scale * <x_img_i, x_anc_c>   (both L2-normalised)
    L            = cross_entropy(logits, labels)

This is exactly zero-shot CLIP's classification rule, made trainable through the
LoRA backbone + projection head. It is the natural Euclidean objective: there is
no entailment hierarchy on the sphere, so the hierarchical caption terms of the
cone loss (image ⊂ caption ⊂ class-anchor) have no direct analogue and are
deliberately omitted — that hierarchy is precisely the capability the hyperbolic
model is meant to add, so leaving it out keeps the baseline honest.
"""
from __future__ import annotations

import torch
import torch.nn as nn
import torch.nn.functional as F


class PrototypeCELoss(nn.Module):
    def __init__(self, max_logit_scale: float = 100.0):
        """max_logit_scale: cap on exp(logit_scale), as in CLIP (default 100)."""
        super().__init__()
        self.max_logit_scale = max_logit_scale

    def forward(
        self,
        x_img: torch.Tensor,        # (B, D)  L2-normalised
        x_anc: torch.Tensor,        # (K, D)  L2-normalised
        labels: torch.Tensor,       # (B,) int in [0, K)
        logit_scale: torch.Tensor,  # scalar, the model's learnable log-temperature
    ) -> tuple[torch.Tensor, dict[str, torch.Tensor]]:
        scale = torch.clamp(logit_scale.exp(), max=self.max_logit_scale)
        logits = scale * (x_img @ x_anc.t())            # (B, K)
        loss = F.cross_entropy(logits, labels)

        with torch.no_grad():
            pred = logits.argmax(dim=1)
            acc = (pred == labels).float().mean()
            cos = x_img @ x_anc.t()                      # (B, K) raw cosines
            cos_pos = cos.gather(1, labels.unsqueeze(1)).squeeze(1).mean()
            # mean cosine to the highest-scoring *wrong* anchor (margin proxy)
            cos_neg = cos.clone()
            cos_neg.scatter_(1, labels.unsqueeze(1), float("-inf"))
            cos_neg_max = cos_neg.max(dim=1).values.mean()

        stats = {
            "acc":          acc.detach(),
            "mean_cos_pos": cos_pos.detach(),
            "mean_cos_neg": cos_neg_max.detach(),
            "logit_scale":  scale.detach(),
        }
        return loss, stats


def predict_class(x_img: torch.Tensor, x_anc: torch.Tensor) -> torch.Tensor:
    """Image-only inference: pick the anchor with the highest cosine similarity."""
    return (x_img @ x_anc.t()).argmax(dim=1)
