"""Class ordering, anchor initialization and geometric state for attribution."""
import math
from pathlib import Path

import torch
from torch import nn
from torch.nn import functional as F
from torch.amp import autocast
from torch.utils.data import DataLoader, WeightedRandomSampler
from tqdm import tqdm
from transformers import CLIPTokenizer

from checkpoint_io import atomic_torch_save
from data.iab_clip_dataset import IABCLIPDataset
from geometry.lorentz import exp_map0, half_aperture
from losses.attribution_loss import _pairwise_xi
from losses.axis_cone_loss import axis_cone_q, depth_from_sin_psi, regular_simplex


def build_anchors(generators: list[str],
                  prompts_path: str | None = None) -> tuple[list[str], list[str]]:
    """Return class names and prompts, placing real first and preserving other order.

    An optional JSON map supplies one prompt per class; all classes must be present."""
    ordered: list[str] = []
    if "real" in generators:
        ordered.append("real")
    for g in generators:
        if g != "real":
            ordered.append(g)

    if prompts_path:
        import json
        with open(prompts_path) as f:
            prompts = json.load(f)
        missing = [c for c in ordered if c not in prompts]
        if missing:
            raise ValueError(f"{prompts_path} has no prompt for {missing}")
        return ordered, [prompts[c] for c in ordered]

    anchor_texts = []
    for c in ordered:
        if c == "real":
            anchor_texts.append("A real image")
        else:
            anchor_texts.append(f"A synthetic image generated by {c}")
    return ordered, anchor_texts

@torch.no_grad()


def class_centroids(core, dataset, class_names, args, device) -> torch.Tensor:
    """Return normalized class means of clean CLIP image features, in class order.

    Use every training row once. An optional cache stores means and class names;
    the caller must choose a cache matching the dataset and backbone."""
    name_to_idx = {n: i for i, n in enumerate(class_names)}
    K = len(class_names)
    cache = Path(args.anchor_init_cache) if args.anchor_init_cache else None
    if cache is not None and cache.exists():
        blob = torch.load(cache, map_location="cpu", weights_only=False)
        if blob["class_names"] != class_names:
            raise ValueError(
                f"anchor cache {cache} was built for {blob['class_names']}, "
                f"not for {class_names}")
        print(f"Anchor centroids: loaded from cache {cache}")
        return blob["mean_clip"]

    was_aug, dataset.train_augment = dataset.train_augment, False
    was_training = core.training
    core.eval()
    loader = DataLoader(dataset, batch_size=args.batch_size, shuffle=False,
                        num_workers=args.num_workers, pin_memory=True)
    clip_dim = core.clip.base_model.model.config.projection_dim
    sums = torch.zeros(K, clip_dim, dtype=torch.float64, device=device)
    counts = torch.zeros(K, dtype=torch.long, device=device)
    for batch in tqdm(loader, desc="anchor centroids"):
        with autocast("cuda"):
            feats = core._clip_image(batch["pixel_values"].to(device))
        labels = torch.tensor([name_to_idx[g] for g in batch["generator"]],
                              device=device, dtype=torch.long)
        sums.index_add_(0, labels, feats.double())
        counts.index_add_(0, labels, torch.ones_like(labels))
    dataset.train_augment = was_aug
    core.train(was_training)

    empty = [c for c, n in zip(class_names, counts.tolist()) if n == 0]
    if empty:
        raise RuntimeError(f"No training images for class(es) {empty} — cannot build anchors")
    mean_clip = F.normalize((sums / counts.unsqueeze(1)).float(), dim=-1).cpu()
    print("Anchor centroids (images per class): "
          + ", ".join(f"{c}={n}" for c, n in zip(class_names, counts.tolist())))

    if cache is not None:
        cache.parent.mkdir(parents=True, exist_ok=True)
        atomic_torch_save({"class_names": class_names, "mean_clip": mean_clip}, cache)
        print(f"Anchor centroids: cached → {cache}")
    return mean_clip


def make_balanced_sampler(dataset: IABCLIPDataset) -> WeightedRandomSampler:
    """K-way balanced sampler: every class sampled with equal probability."""
    from collections import Counter
    counts = Counter(g for _, g, _ in dataset.samples)
    if len(counts) < 2:
        raise RuntimeError(f"Dataset needs at least 2 classes, got: {dict(counts)}")
    weights = [1.0 / counts[g] for _, g, _ in dataset.samples]
    print(f"Balanced sampler classes: {dict(counts)}")
    return WeightedRandomSampler(weights, num_samples=len(dataset), replacement=True)


class AnchorState:
    """Class anchor tensors and axis apertures used by training.

    Text anchors are encoded by the model on demand. Free anchors store tangent
    parameters; text_free adds a learned scaled offset to a fixed reference.
    """

    def __init__(self, model, train_ds, class_names, anchor_texts, args, device):
        self.anchor_tangent = None
        self.anchor_t0 = self.anchor_delta = self.anchor_drift = None

        tokenizer = CLIPTokenizer.from_pretrained(args.clip_name)
        anchor_tok = tokenizer(anchor_texts, return_tensors="pt", padding="max_length",
                               truncation=True, max_length=77)
        self.anchor_ids  = anchor_tok["input_ids"].to(device)
        self.anchor_mask = anchor_tok["attention_mask"].to(device)

        if args.anchor_init != "text":
            with torch.no_grad():
                if args.anchor_init == "random":
                    g = torch.Generator().manual_seed(args.seed)
                    t0 = torch.randn(len(class_names), args.hyperbolic_dim,
                                     generator=g).to(device)
                elif args.anchor_init == "simplex":
                    t0 = regular_simplex(len(class_names), args.hyperbolic_dim,
                                         device=device, dtype=torch.float32)
                elif args.anchor_init == "image_centroid":
                    t0 = model.projection(
                        class_centroids(model, train_ds, class_names, args, device).to(device))
                else:
                    _, t0 = model.encode_text(self.anchor_ids, self.anchor_mask)
                if args.anchor_init_norm > 0:
                    t0 = F.normalize(t0, dim=-1) * args.anchor_init_norm
                t0 = t0.detach().float()

            if args.anchor_init in ("image_centroid", "random", "simplex"):
                self.anchor_tangent = nn.Parameter(t0, requires_grad=not args.freeze_anchors)
            else:
                self.anchor_t0 = t0                                        # fixed reference
                self.anchor_delta = nn.Parameter(torch.zeros_like(t0))
                self.anchor_drift = nn.Parameter(
                    torch.tensor(float(args.anchor_drift_init)).expm1().clamp(min=1e-6).log())

            with torch.no_grad():
                psi0 = half_aperture(exp_map0(t0, curv=args.curv),
                                     curv=args.curv, min_radius=args.min_radius)
                d = F.normalize(t0, dim=-1)
                cos = (d @ d.T).clamp(-1, 1)
                iu = torch.triu_indices(len(class_names), len(class_names), offset=1)
                ang = torch.arccos(cos[iu[0], iu[1]])     # off-diagonal pairs only
            psi_lo_d, psi_hi_d = args.psi_range
            if args.loss == "axis" and args.fixed_psi:
                psi_txt = f"ψ={args.fixed_psi:.1f}° (fixed during classifier training)"
            elif args.loss == "axis":
                psi_txt = f"ψ={0.5 * (psi_lo_d + psi_hi_d):.1f}° (free, mid --psi_range)"
            else:
                psi_txt = f"ψ={math.degrees(psi0.mean()):.1f}° (=asin(2K/‖a‖))"
            print(f"Anchor init ({args.anchor_init}): ‖t‖={t0.norm(dim=-1).mean():.2f}  "
                  f"{psi_txt}  min∠={math.degrees(ang.min()):.1f}°  "
                  f"mean∠={math.degrees(ang.mean()):.1f}°  (K={len(class_names)})")
            if args.freeze_anchors:
                print("Anchor directions: frozen")
            if args.freeze_anchors and args.fixed_psi:
                required_sep = 2 * args.fixed_psi + args.separation_margin
                if math.degrees(ang.min()) + 1e-4 < required_sep:
                    raise ValueError(f"Fixed cones overlap at init: min axis angle "
                                     f"{math.degrees(ang.min()):.2f}° < required "
                                     f"{required_sep:.2f}°")
            if args.loss != "axis" and ang.min() < 2 * psi0.mean():
                print(f"  ⚠️  closest anchor pair is inside "
                      f"2ψ={math.degrees(2 * psi0.mean()):.1f}° — those cones overlap at init")
            if self.anchor_drift is not None:
                print(f"  drift scale s={F.softplus(self.anchor_drift).item():.3f} (learned)")

        self.anchor_psi_raw = None
        self.fixed_sin_psi = None
        self.psi_lo, self.psi_hi = (math.radians(v) for v in args.psi_range)
        if args.loss == "axis":
            if args.fixed_psi:
                self.fixed_sin_psi = torch.full(
                    (len(class_names),), math.sin(math.radians(args.fixed_psi)), device=device)
            else:
                self.anchor_psi_raw = nn.Parameter(torch.zeros(len(class_names), device=device))
            if self.anchor_tangent is not None:
                with torch.no_grad():
                    rc = args.curv ** 0.5
                    sp0 = (self.fixed_sin_psi if self.fixed_sin_psi is not None else
                           torch.sin(self.psi_lo + (self.psi_hi - self.psi_lo)
                                     * torch.sigmoid(self.anchor_psi_raw)))
                    want = torch.asinh(rc * depth_from_sin_psi(sp0, args.min_radius)) / rc
                    self.anchor_tangent.mul_(
                        want.unsqueeze(1)
                        / self.anchor_tangent.norm(dim=-1, keepdim=True).clamp_min(1e-8))

    def sin_psi(self):
        """(K,) sine of each half-aperture, or None outside the axis loss."""
        if self.fixed_sin_psi is not None:
            return self.fixed_sin_psi
        if self.anchor_psi_raw is None:
            return None
        return torch.sin(self.psi_lo + (self.psi_hi - self.psi_lo) * torch.sigmoid(self.anchor_psi_raw))

    def tangent(self):
        """Current tangent anchors (K, D_hyp), or None in plain 'text' mode."""
        if self.anchor_delta is not None:
            return self.anchor_t0 + F.softplus(self.anchor_drift) * self.anchor_delta
        return self.anchor_tangent

    @torch.no_grad()
    def project_(self, args):
        """Update free anchor depths from apertures or clamp cone tangent norms."""
        if args.loss == "axis" and self.anchor_tangent is not None:
            with torch.no_grad():
                rc = args.curv ** 0.5
                want = torch.asinh(
                    rc * depth_from_sin_psi(self.sin_psi(), args.min_radius)) / rc
                n = self.anchor_tangent.norm(dim=-1, keepdim=True).clamp_min(1e-8)
                self.anchor_tangent.mul_(want.unsqueeze(1) / n)
        elif args.anchor_norm_range and self.anchor_tangent is not None:
            lo, hi = args.anchor_norm_range
            with torch.no_grad():
                n = self.anchor_tangent.norm(dim=-1, keepdim=True)
                self.anchor_tangent.mul_(n.clamp(lo, hi) / n.clamp_min(1e-8))

    def parameters(self):
        """Trainable geometric tensors, in optimizer/checkpoint-compatible order."""
        return [p for p in (self.anchor_tangent, self.anchor_delta,
                            self.anchor_drift, self.anchor_psi_raw)
                if p is not None and p.requires_grad]

    def snapshot_psi(self):
        """Return axis half-apertures in radians, or None for cone loss."""
        value = self.sin_psi()
        return torch.arcsin(value).detach().float().cpu().numpy() if value is not None else None


def calibrate_image_depth(model, train_loader, anchors, args, device):
    """Apply optional head rescaling, report depths and check cone initialization."""
    model.eval()
    with torch.no_grad():
        probe = next(iter(train_loader))["pixel_values"][:64].to(device)
        if args.init_depth > 0:
            cur = model.encode_image(probe)[1].norm(dim=-1).median().item()
            k = args.init_depth / max(cur, 1e-12)
            model.projection[-1].weight.mul_(k)
            model.projection[-1].bias.mul_(k)
            print(f"Head calibrated for --init_depth: ‖t_img‖ {cur:.4f} → "
                  f"{args.init_depth:.2f} (last layer ×{k:.1f})")
        x_probe, t_probe = model.encode_image(probe)
        t_now = anchors.tangent()
        x_anc0 = (exp_map0(t_now.float(), curv=args.curv) if t_now is not None
                  else model.encode_text(anchors.anchor_ids, anchors.anchor_mask)[0])
        if args.loss == "axis":
            psi0 = torch.arcsin(anchors.sin_psi())
            q0 = axis_cone_q(x_probe, x_anc0, anchors.sin_psi())
        else:
            psi0 = half_aperture(x_anc0, curv=args.curv, min_radius=args.min_radius)
            xi0 = _pairwise_xi(x_anc0, x_probe, curv=args.curv)
            pinned = (xi0 > math.pi - 5e-3).float().mean().item()
    if args.anchors_only:
        model.requires_grad_(False)
        model.eval()
        print("Anchors-only: CLIP+LoRA and projection head frozen in eval mode")
    else:
        model.train()
    t_img = t_probe.norm(dim=-1).median().item()
    x_img = x_probe.norm(dim=-1).median().item()
    x_anc_n = x_anc0.norm(dim=-1).median().item()
    x_anc_max = x_anc0.norm(dim=-1).max().item()
    print(f"Image depth at init: ‖t_img‖={t_img:.3f} ‖x_img‖={x_img:.3f}  vs  "
          f"‖x_anc‖={x_anc_n:.3f} (max {x_anc_max:.3f})")
    if args.loss == "axis":
        print(f"  q(image, cone) median {q0.median().item():.3f}  "
              f"min {q0.min().item():.3f}  "
              f"ψ∈[{math.degrees(psi0.min()):.1f},{math.degrees(psi0.max()):.1f}]°  "
              f"(q=1 is the cone wall)")
    else:
        print(f"  ξ(anchor→image) median {xi0.median().item():.3f} rad "
              f"({math.degrees(xi0.median().item()):.1f}°)  ψ={psi0.median().item():.3f}  "
              f"{100 * pinned:.0f}% pinned at π   (images must be DEEPER than anchors)")
        if x_img <= x_anc_max:
            want = 1.5 * math.asinh(x_anc_max)
            raise ValueError(
                f"containment INVERTED: median image depth ‖x_img‖={x_img:.4f} is not "
                f"above the DEEPEST anchor ‖x_anc‖={x_anc_max:.4f}. An entailment cone "
                f"holds the points farther from the origin than its apex, so every ξ "
                f"sits at π and oxy_angle's acos clamp makes the gradient exactly zero "
                f"— no learning rate moves it.\n"
                f"    Fix: --init_depth {want:.2f}  (1.5x the deepest anchor's tangent "
                f"norm, giving ‖x_img‖≈{math.sinh(want):.1f})."
            )
        if pinned > 0.05:
            print(f"  ⚠️  {100 * pinned:.0f}% of the ξ matrix is pinned at π even though "
                  f"the depth ordering is right — check the anchor spread.")
