"""
Generator → family taxonomy for the hierarchical entailment-cone attribution.

A *family* is a broad generator lineage (e.g. all Stable Diffusion variants) that
sits one level above the individual generator in the cone hierarchy:

    family cone ("A synthetic image generated by a Stable Diffusion model")
        ⊃ generator cone ("A synthetic image generated by SD3_5")
            ⊃ image

Only lineages with ≥2 members in the IAB set form a real multi-member family
(Stable Diffusion, Midjourney, OpenAI). Every other generator is a *singleton*
family: its family cone coincides with its generator cone, so its family anchor
text is identical to its class anchor text. ``real`` is a singleton family too.

This module is shared by training (train_attribution.py) and the hierarchical
evaluation (tests/eval_attribution_hierarchical.py) so the taxonomy is defined
in exactly one place. The family of a held-out generator (one excluded from
training) is still well-defined here, which is what makes novelty detection
measurable.
"""
from __future__ import annotations

# Class-anchor templates — kept identical to train_attribution.build_anchors so
# that a singleton family's anchor text matches its generator anchor text.
REAL_ANCHOR = "A real image"
GEN_ANCHOR_TEMPLATE = "A synthetic image generated by {gen}"


# ── Multi-member lineages: generator → family display name ────────────────────
_LINEAGE: dict[str, str] = {
    "SD1_5": "Stable Diffusion",
    "SD2_1": "Stable Diffusion",
    "SD3":   "Stable Diffusion",
    "SD3_5": "Stable Diffusion",
    "SDXL":  "Stable Diffusion",
    "mid-5.2": "Midjourney",
    "mid-6.0": "Midjourney",
    "4o":     "OpenAI",
    "dalle3": "OpenAI",
}

# Natural-language anchor text for each multi-member family.
_FAMILY_ANCHOR: dict[str, str] = {
    "Stable Diffusion": "A synthetic image generated by a Stable Diffusion model",
    "Midjourney":       "A synthetic image generated by a Midjourney model",
    "OpenAI":           "A synthetic image generated by an OpenAI model",
}


def family_of(generator: str) -> str:
    """Return the family name of a generator.

    Generators in a known multi-member lineage map to that lineage; every other
    generator (including ``real``) is its own singleton family.
    """
    return _LINEAGE.get(generator, generator)


def family_anchor_text(family: str) -> str:
    """Natural-language anchor for a family cone.

    - ``real``               → "A real image"
    - multi-member family     → its generic lineage anchor
    - singleton (family == generator name) → the generator class-anchor template,
      so the family cone coincides with the generator cone.
    """
    if family == "real":
        return REAL_ANCHOR
    if family in _FAMILY_ANCHOR:
        return _FAMILY_ANCHOR[family]
    return GEN_ANCHOR_TEMPLATE.format(gen=family)


def build_family_structures(
    class_names: list[str],
) -> tuple[list[str], list[str], list[int]]:
    """Build the family-level structures parallel to the generator classes.

    Args:
        class_names: Ordered generator names (label k ↔ class_names[k]), as
            produced by train_attribution.build_anchors. ``real`` first if present.

    Returns:
        family_names:        Ordered, de-duplicated family names (first-appearance order).
        family_anchor_texts: family_anchor_text(f) for each f in family_names.
        gen_to_family_idx:   gen_to_family_idx[k] = index into family_names of the
                             family of class k.
    """
    family_names: list[str] = []
    family_to_idx: dict[str, int] = {}
    gen_to_family_idx: list[int] = []
    for gen in class_names:
        fam = family_of(gen)
        if fam not in family_to_idx:
            family_to_idx[fam] = len(family_names)
            family_names.append(fam)
        gen_to_family_idx.append(family_to_idx[fam])

    family_anchor_texts = [family_anchor_text(f) for f in family_names]
    return family_names, family_anchor_texts, gen_to_family_idx
