"""
Fair evaluation of the hyperbolic-CLIP attributor on ImageAttributionBench,
under a protocol BYTE-IDENTICAL to the comparison baselines.

It reuses the baselines' own machinery so nothing about the protocol can drift:
  - `get_dataloader(model_name='hypclip', ...)` → same enumeration, same
    stratified 80/10/10 split (seed 42), same 2000/semantic cap, same
    test-time degradation as resnet50/dct/hifi_net/defl (→ identical test images).
  - `calculate_metrics_for_test(...)` → identical acc / macro-AUC / macro-AP /
    confusion matrix / per-semantic acc / precision-recall-F1.

The only model-specific part is turning the hyperbolic cone geometry into
per-class logits: for anchor c and image i we use logits[i, c] = -xi(anchor_c, img_i),
where xi = oxy_angle (exterior angle to the cone apex). Since the model's decision
rule is argmin_c xi (see losses.attribution_loss.predict_class), argmax over these
logits reproduces EXACTLY the model's own prediction, and softmax(-xi) feeds AUC/AP.

Usage (on CINECA, via SLURM):
    python -m comparison.training.test_hypclip \\
        --checkpoint $WORK/hyp_fine_tuning/checkpoints/attribution_23cls_vitl14.pt \\
        --root_dir   $FAST/datasets/iab_dataset \\
        --level_start 0 --level_end 7 \\
        --log_dir    $WORK/outputs/hypclip_fair
"""
import os
import argparse
import datetime

import torch
from tqdm import tqdm

from comparison.dataset.ImageAttributionDataset.dataloader import get_dataloader
from comparison.dataset.ImageAttributionDataset.semantic_split import get_semantic
from comparison.dataset.ImageAttributionDataset.dataset import model_class_to_label
from comparison.training.metrics.base_metrics_class import calculate_metrics_for_test

from models.attribution_clip import AttributionCLIP
from geometry.lorentz import exp_map0, oxy_angle
from data.degradations import LEVEL_LABELS
from transformers import CLIPTokenizer


def parse_args():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument('--checkpoint', required=True, help='our native .pt checkpoint')
    p.add_argument('--root_dir', required=True, help='root of the IAB dataset')
    p.add_argument('--batch_size', type=int, default=64)
    p.add_argument('--num_workers', type=int, default=4)
    p.add_argument('--num_images_per_semantic_per_class', '-n', type=int, default=2000)
    p.add_argument('--level_start', type=int, default=0)
    p.add_argument('--level_end', type=int, default=1, help='exclusive (0..7 covers all)')
    p.add_argument('--use_semantic_split', action='store_true', default=False)
    p.add_argument('--task_id', type=int, default=1)
    p.add_argument('--log_dir', type=str, default='./logs_test_hypclip')
    p.add_argument('--pre_resize', type=int, default=0,
                   help='CONTROL, off by default. Square every test image to NxN before '
                        'the CLIP processor. Normally the processor resizes the shortest '
                        'edge to 224, so the native->224 ratio differs per class — and '
                        'tests/audit_shortcuts.py shows native resolution is strongly '
                        'class-dependent, i.e. the resampling signature is a candidate '
                        'shortcut. Pre-resizing makes that ratio the SAME for every image. '
                        'A large accuracy drop means we were reading resolution; a small '
                        'one means the fingerprints are real. Suggested: 512. Runs marked '
                        'with it are a control, never a headline number.')
    return p.parse_args()


def harness_class_names():
    """Class names in the harness label order (index 0..K-1)."""
    idx_to_name = {v: k for k, v in model_class_to_label.items()}
    return [idx_to_name[i] for i in range(len(idx_to_name))]


def build_anchor_texts():
    """Anchor texts in the harness label order (index 0..K-1)."""
    return ["A real image" if name == 'real'
            else f"A synthetic image generated by {name}"
            for name in harness_class_names()]


def load_anchors(ckpt, model, curv, device):
    """Class anchors in the HARNESS label order → logits column c == label c.

    Both anchor kinds live in the checkpoint's OWN class order ('real' first) and
    are permuted here into the harness order ('real' last):
      - free anchors (image_centroid / text_free) → 'anchor_tangent', lifted with exp_map0;
      - text anchors → re-encoded from the checkpoint's OWN 'anchor_texts'.

    Re-encoding from the checkpoint rather than from build_anchor_texts() is what
    makes --anchor_prompts safe: a run trained on different prompts would otherwise
    be evaluated against the default templates, silently and without any error.
    """
    ckpt_names = list(ckpt['class_names'])
    harness_names = harness_class_names()
    missing = [n for n in harness_names if n not in ckpt_names]
    if missing:
        raise ValueError(f"checkpoint has no anchor for class(es) {missing}; "
                         f"it was trained on {ckpt_names}")
    perm = [ckpt_names.index(n) for n in harness_names]

    tangent = ckpt.get('anchor_tangent')
    if tangent is not None:
        print(f"Anchors: {len(perm)} learned {ckpt.get('anchor_init', 'free')} anchors "
              f"(reordered {ckpt_names[:2]}… → harness order)")
        return exp_map0(tangent[perm].float().to(device), curv=curv)

    ckpt_texts = ckpt.get('anchor_texts')
    if ckpt_texts:
        anchor_texts = [ckpt_texts[i] for i in perm]
        src = 'checkpoint prompts'
    else:
        anchor_texts = build_anchor_texts()      # pre-anchor_texts checkpoints
        src = 'default templates'
    tokenizer = CLIPTokenizer.from_pretrained(ckpt['clip_name'])
    tok = tokenizer(anchor_texts, return_tensors='pt', padding='max_length',
                    truncation=True, max_length=77)
    print(f"Anchors: {len(anchor_texts)} text anchors from {src}")
    print(f"  [0] {harness_names[0]} → \"{anchor_texts[0]}\"")
    x_anc, _ = model.encode_text(tok['input_ids'].to(device),
                                 tok['attention_mask'].to(device))
    return x_anc


@torch.no_grad()
def main():
    args = parse_args()
    device = 'cuda' if torch.cuda.is_available() else 'cpu'

    ckpt = torch.load(args.checkpoint, map_location=device, weights_only=False)
    clip_name = ckpt['clip_name']
    curv = ckpt.get('curv', 1.0)

    model = AttributionCLIP(
        clip_name=clip_name,
        lora_r=ckpt.get('lora_r', 8),
        lora_alpha=ckpt.get('lora_alpha', 16),
        hyperbolic_dim=ckpt.get('hyperbolic_dim', 128),
        curv=curv,
    ).to(device)
    model.clip.load_state_dict(ckpt['lora_state'])
    model.projection.load_state_dict(ckpt['projection'])
    model.eval()

    x_anc = load_anchors(ckpt, model, curv, device)                    # (K, D)
    K = x_anc.shape[0]

    os.makedirs(args.log_dir, exist_ok=True)
    config = {'model_name': 'hypclip', 'clip_name': clip_name, 'num_classes': K,
              'pre_resize': args.pre_resize}
    if args.pre_resize:
        print(f"CONTROL RUN: every test image squared to {args.pre_resize}x"
              f"{args.pre_resize} first — the native->224 resampling ratio is now "
              f"constant across classes. Not a head-to-head number.")

    train_semantics = test_semantics = None
    if args.use_semantic_split:
        train_semantics, test_semantics = get_semantic(args.task_id)

    for degraded in range(args.level_start, args.level_end):
        deg_label = LEVEL_LABELS.get(degraded, str(degraded))
        print(f"\n=== degraded={degraded} ({deg_label}) ===")

        _, _, test_loader = get_dataloader(
            root_dir=args.root_dir,
            model_name='hypclip',
            num_images_per_semantic_per_class=args.num_images_per_semantic_per_class,
            batch_size=args.batch_size,
            degraded=degraded,
            config=config,
            num_workers=args.num_workers,
            use_semantic_split=args.use_semantic_split,
            train_semantics=train_semantics,
            test_semantics=test_semantics,
        )

        all_logits, all_labels, all_sem = [], [], []
        for batch in tqdm(test_loader, total=len(test_loader), desc=f"deg{degraded}"):
            pixel = batch['image'].to(device)
            x_img, _ = model.encode_image(pixel)                        # (B, D)
            B = x_img.shape[0]
            x_anc_t = x_anc.unsqueeze(0).expand(B, K, -1).reshape(B * K, -1)
            x_img_t = x_img.unsqueeze(1).expand(B, K, -1).reshape(B * K, -1)
            xi = oxy_angle(x_anc_t, x_img_t, curv=curv).reshape(B, K)   # (B, 23)
            all_logits.append((-xi).cpu())
            all_labels.append(batch['label'].cpu())
            all_sem.append(batch['semantic_label'].cpu())

        logits = torch.cat(all_logits, dim=0)
        labels = torch.cat(all_labels, dim=0)
        sem = torch.cat(all_sem, dim=0)

        auc, acc, ap, conf_matrix, semantic_acc, extra = \
            calculate_metrics_for_test(labels, logits, sem, need_softmax=True)

        out_path = os.path.join(args.log_dir, f"test_results_degraded_{degraded}.txt")
        with open(out_path, 'w') as f:
            f.write(f"Test metrics for degraded={degraded} ({deg_label}) "
                    f"({datetime.datetime.now()}):\n")
            f.write(f"acc: {acc}\n")
            f.write(f"auc: {auc}\n")
            f.write(f"ap: {ap}\n")
            for k, v in extra.items():
                f.write(f"{k}: {v}\n")
            f.write(f"semantic_acc: {semantic_acc}\n")
            f.write(f"conf_matrix:\n{conf_matrix}\n")
        print(f"  acc={acc:.4f}  auc={auc:.4f}  ap={ap:.4f}  "
              f"P_macro={extra['precision_macro']:.4f}  R_macro={extra['recall_macro']:.4f}")
        print(f"  saved → {out_path}")


if __name__ == '__main__':
    main()
